// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLastName holds the string denoting the last_name field in the database.
	FieldLastName = "last_name"
	// FieldIsAdmin holds the string denoting the is_admin field in the database.
	FieldIsAdmin = "is_admin"
	// FieldTotpSecret holds the string denoting the totp_secret field in the database.
	FieldTotpSecret = "totp_secret"
	// FieldTotpEnabled holds the string denoting the totp_enabled field in the database.
	FieldTotpEnabled = "totp_enabled"
	// FieldBackupCodes holds the string denoting the backup_codes field in the database.
	FieldBackupCodes = "backup_codes"
	// FieldPasswordChangedAt holds the string denoting the password_changed_at field in the database.
	FieldPasswordChangedAt = "password_changed_at"
	// FieldInviteCount holds the string denoting the invite_count field in the database.
	FieldInviteCount = "invite_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOwnedProjects holds the string denoting the owned_projects edge name in mutations.
	EdgeOwnedProjects = "owned_projects"
	// EdgeOwnedTeams holds the string denoting the owned_teams edge name in mutations.
	EdgeOwnedTeams = "owned_teams"
	// EdgeTeamMemberships holds the string denoting the team_memberships edge name in mutations.
	EdgeTeamMemberships = "team_memberships"
	// EdgeProjectMemberships holds the string denoting the project_memberships edge name in mutations.
	EdgeProjectMemberships = "project_memberships"
	// EdgeProjectMembershipsGranted holds the string denoting the project_memberships_granted edge name in mutations.
	EdgeProjectMembershipsGranted = "project_memberships_granted"
	// EdgeTasksAssigned holds the string denoting the tasks_assigned edge name in mutations.
	EdgeTasksAssigned = "tasks_assigned"
	// EdgeTaskAssignees holds the string denoting the task_assignees edge name in mutations.
	EdgeTaskAssignees = "task_assignees"
	// EdgeSprints holds the string denoting the sprints edge name in mutations.
	EdgeSprints = "sprints"
	// EdgeTags holds the string denoting the tags edge name in mutations.
	EdgeTags = "tags"
	// EdgeAPIKeys holds the string denoting the api_keys edge name in mutations.
	EdgeAPIKeys = "api_keys"
	// EdgeUserActivities holds the string denoting the user_activities edge name in mutations.
	EdgeUserActivities = "user_activities"
	// EdgeTaskComments holds the string denoting the task_comments edge name in mutations.
	EdgeTaskComments = "task_comments"
	// EdgeInvitesSent holds the string denoting the invites_sent edge name in mutations.
	EdgeInvitesSent = "invites_sent"
	// EdgeInvitesReceived holds the string denoting the invites_received edge name in mutations.
	EdgeInvitesReceived = "invites_received"
	// EdgeTeamInvitationsSent holds the string denoting the team_invitations_sent edge name in mutations.
	EdgeTeamInvitationsSent = "team_invitations_sent"
	// EdgeTeamInvitationsReceived holds the string denoting the team_invitations_received edge name in mutations.
	EdgeTeamInvitationsReceived = "team_invitations_received"
	// EdgeCloudinaryCredentials holds the string denoting the cloudinary_credentials edge name in mutations.
	EdgeCloudinaryCredentials = "cloudinary_credentials"
	// EdgeTaskAttachments holds the string denoting the task_attachments edge name in mutations.
	EdgeTaskAttachments = "task_attachments"
	// EdgeWikiPagesCreated holds the string denoting the wiki_pages_created edge name in mutations.
	EdgeWikiPagesCreated = "wiki_pages_created"
	// EdgeYjsUpdates holds the string denoting the yjs_updates edge name in mutations.
	EdgeYjsUpdates = "yjs_updates"
	// Table holds the table name of the user in the database.
	Table = "users"
	// OwnedProjectsTable is the table that holds the owned_projects relation/edge.
	OwnedProjectsTable = "projects"
	// OwnedProjectsInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	OwnedProjectsInverseTable = "projects"
	// OwnedProjectsColumn is the table column denoting the owned_projects relation/edge.
	OwnedProjectsColumn = "owner_id"
	// OwnedTeamsTable is the table that holds the owned_teams relation/edge.
	OwnedTeamsTable = "teams"
	// OwnedTeamsInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	OwnedTeamsInverseTable = "teams"
	// OwnedTeamsColumn is the table column denoting the owned_teams relation/edge.
	OwnedTeamsColumn = "owner_id"
	// TeamMembershipsTable is the table that holds the team_memberships relation/edge.
	TeamMembershipsTable = "team_members"
	// TeamMembershipsInverseTable is the table name for the TeamMember entity.
	// It exists in this package in order to avoid circular dependency with the "teammember" package.
	TeamMembershipsInverseTable = "team_members"
	// TeamMembershipsColumn is the table column denoting the team_memberships relation/edge.
	TeamMembershipsColumn = "user_id"
	// ProjectMembershipsTable is the table that holds the project_memberships relation/edge.
	ProjectMembershipsTable = "project_members"
	// ProjectMembershipsInverseTable is the table name for the ProjectMember entity.
	// It exists in this package in order to avoid circular dependency with the "projectmember" package.
	ProjectMembershipsInverseTable = "project_members"
	// ProjectMembershipsColumn is the table column denoting the project_memberships relation/edge.
	ProjectMembershipsColumn = "user_id"
	// ProjectMembershipsGrantedTable is the table that holds the project_memberships_granted relation/edge.
	ProjectMembershipsGrantedTable = "project_members"
	// ProjectMembershipsGrantedInverseTable is the table name for the ProjectMember entity.
	// It exists in this package in order to avoid circular dependency with the "projectmember" package.
	ProjectMembershipsGrantedInverseTable = "project_members"
	// ProjectMembershipsGrantedColumn is the table column denoting the project_memberships_granted relation/edge.
	ProjectMembershipsGrantedColumn = "granted_by"
	// TasksAssignedTable is the table that holds the tasks_assigned relation/edge.
	TasksAssignedTable = "tasks"
	// TasksAssignedInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TasksAssignedInverseTable = "tasks"
	// TasksAssignedColumn is the table column denoting the tasks_assigned relation/edge.
	TasksAssignedColumn = "assignee_id"
	// TaskAssigneesTable is the table that holds the task_assignees relation/edge.
	TaskAssigneesTable = "task_assignees"
	// TaskAssigneesInverseTable is the table name for the TaskAssignee entity.
	// It exists in this package in order to avoid circular dependency with the "taskassignee" package.
	TaskAssigneesInverseTable = "task_assignees"
	// TaskAssigneesColumn is the table column denoting the task_assignees relation/edge.
	TaskAssigneesColumn = "user_id"
	// SprintsTable is the table that holds the sprints relation/edge.
	SprintsTable = "sprints"
	// SprintsInverseTable is the table name for the Sprint entity.
	// It exists in this package in order to avoid circular dependency with the "sprint" package.
	SprintsInverseTable = "sprints"
	// SprintsColumn is the table column denoting the sprints relation/edge.
	SprintsColumn = "user_id"
	// TagsTable is the table that holds the tags relation/edge.
	TagsTable = "tags"
	// TagsInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagsInverseTable = "tags"
	// TagsColumn is the table column denoting the tags relation/edge.
	TagsColumn = "user_id"
	// APIKeysTable is the table that holds the api_keys relation/edge.
	APIKeysTable = "api_keys"
	// APIKeysInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeysInverseTable = "api_keys"
	// APIKeysColumn is the table column denoting the api_keys relation/edge.
	APIKeysColumn = "user_id"
	// UserActivitiesTable is the table that holds the user_activities relation/edge.
	UserActivitiesTable = "user_activity"
	// UserActivitiesInverseTable is the table name for the UserActivity entity.
	// It exists in this package in order to avoid circular dependency with the "useractivity" package.
	UserActivitiesInverseTable = "user_activity"
	// UserActivitiesColumn is the table column denoting the user_activities relation/edge.
	UserActivitiesColumn = "user_id"
	// TaskCommentsTable is the table that holds the task_comments relation/edge.
	TaskCommentsTable = "task_comments"
	// TaskCommentsInverseTable is the table name for the TaskComment entity.
	// It exists in this package in order to avoid circular dependency with the "taskcomment" package.
	TaskCommentsInverseTable = "task_comments"
	// TaskCommentsColumn is the table column denoting the task_comments relation/edge.
	TaskCommentsColumn = "user_id"
	// InvitesSentTable is the table that holds the invites_sent relation/edge.
	InvitesSentTable = "invites"
	// InvitesSentInverseTable is the table name for the Invite entity.
	// It exists in this package in order to avoid circular dependency with the "invite" package.
	InvitesSentInverseTable = "invites"
	// InvitesSentColumn is the table column denoting the invites_sent relation/edge.
	InvitesSentColumn = "inviter_id"
	// InvitesReceivedTable is the table that holds the invites_received relation/edge.
	InvitesReceivedTable = "invites"
	// InvitesReceivedInverseTable is the table name for the Invite entity.
	// It exists in this package in order to avoid circular dependency with the "invite" package.
	InvitesReceivedInverseTable = "invites"
	// InvitesReceivedColumn is the table column denoting the invites_received relation/edge.
	InvitesReceivedColumn = "invitee_id"
	// TeamInvitationsSentTable is the table that holds the team_invitations_sent relation/edge.
	TeamInvitationsSentTable = "team_invitations"
	// TeamInvitationsSentInverseTable is the table name for the TeamInvitation entity.
	// It exists in this package in order to avoid circular dependency with the "teaminvitation" package.
	TeamInvitationsSentInverseTable = "team_invitations"
	// TeamInvitationsSentColumn is the table column denoting the team_invitations_sent relation/edge.
	TeamInvitationsSentColumn = "inviter_id"
	// TeamInvitationsReceivedTable is the table that holds the team_invitations_received relation/edge.
	TeamInvitationsReceivedTable = "team_invitations"
	// TeamInvitationsReceivedInverseTable is the table name for the TeamInvitation entity.
	// It exists in this package in order to avoid circular dependency with the "teaminvitation" package.
	TeamInvitationsReceivedInverseTable = "team_invitations"
	// TeamInvitationsReceivedColumn is the table column denoting the team_invitations_received relation/edge.
	TeamInvitationsReceivedColumn = "invitee_id"
	// CloudinaryCredentialsTable is the table that holds the cloudinary_credentials relation/edge.
	CloudinaryCredentialsTable = "cloudinary_credentials"
	// CloudinaryCredentialsInverseTable is the table name for the CloudinaryCredential entity.
	// It exists in this package in order to avoid circular dependency with the "cloudinarycredential" package.
	CloudinaryCredentialsInverseTable = "cloudinary_credentials"
	// CloudinaryCredentialsColumn is the table column denoting the cloudinary_credentials relation/edge.
	CloudinaryCredentialsColumn = "user_id"
	// TaskAttachmentsTable is the table that holds the task_attachments relation/edge.
	TaskAttachmentsTable = "task_attachments"
	// TaskAttachmentsInverseTable is the table name for the TaskAttachment entity.
	// It exists in this package in order to avoid circular dependency with the "taskattachment" package.
	TaskAttachmentsInverseTable = "task_attachments"
	// TaskAttachmentsColumn is the table column denoting the task_attachments relation/edge.
	TaskAttachmentsColumn = "user_id"
	// WikiPagesCreatedTable is the table that holds the wiki_pages_created relation/edge.
	WikiPagesCreatedTable = "wiki_pages"
	// WikiPagesCreatedInverseTable is the table name for the WikiPage entity.
	// It exists in this package in order to avoid circular dependency with the "wikipage" package.
	WikiPagesCreatedInverseTable = "wiki_pages"
	// WikiPagesCreatedColumn is the table column denoting the wiki_pages_created relation/edge.
	WikiPagesCreatedColumn = "created_by"
	// YjsUpdatesTable is the table that holds the yjs_updates relation/edge.
	YjsUpdatesTable = "yjs_updates"
	// YjsUpdatesInverseTable is the table name for the YjsUpdate entity.
	// It exists in this package in order to avoid circular dependency with the "yjsupdate" package.
	YjsUpdatesInverseTable = "yjs_updates"
	// YjsUpdatesColumn is the table column denoting the yjs_updates relation/edge.
	YjsUpdatesColumn = "created_by"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldPasswordHash,
	FieldName,
	FieldFirstName,
	FieldLastName,
	FieldIsAdmin,
	FieldTotpSecret,
	FieldTotpEnabled,
	FieldBackupCodes,
	FieldPasswordChangedAt,
	FieldInviteCount,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// DefaultIsAdmin holds the default value on creation for the "is_admin" field.
	DefaultIsAdmin bool
	// DefaultTotpEnabled holds the default value on creation for the "totp_enabled" field.
	DefaultTotpEnabled bool
	// DefaultInviteCount holds the default value on creation for the "invite_count" field.
	DefaultInviteCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByFirstName orders the results by the first_name field.
func ByFirstName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstName, opts...).ToFunc()
}

// ByLastName orders the results by the last_name field.
func ByLastName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastName, opts...).ToFunc()
}

// ByIsAdmin orders the results by the is_admin field.
func ByIsAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAdmin, opts...).ToFunc()
}

// ByTotpSecret orders the results by the totp_secret field.
func ByTotpSecret(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotpSecret, opts...).ToFunc()
}

// ByTotpEnabled orders the results by the totp_enabled field.
func ByTotpEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotpEnabled, opts...).ToFunc()
}

// ByBackupCodes orders the results by the backup_codes field.
func ByBackupCodes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackupCodes, opts...).ToFunc()
}

// ByPasswordChangedAt orders the results by the password_changed_at field.
func ByPasswordChangedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordChangedAt, opts...).ToFunc()
}

// ByInviteCount orders the results by the invite_count field.
func ByInviteCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOwnedProjectsCount orders the results by owned_projects count.
func ByOwnedProjectsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOwnedProjectsStep(), opts...)
	}
}

// ByOwnedProjects orders the results by owned_projects terms.
func ByOwnedProjects(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnedProjectsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOwnedTeamsCount orders the results by owned_teams count.
func ByOwnedTeamsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOwnedTeamsStep(), opts...)
	}
}

// ByOwnedTeams orders the results by owned_teams terms.
func ByOwnedTeams(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnedTeamsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTeamMembershipsCount orders the results by team_memberships count.
func ByTeamMembershipsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeamMembershipsStep(), opts...)
	}
}

// ByTeamMemberships orders the results by team_memberships terms.
func ByTeamMemberships(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamMembershipsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProjectMembershipsCount orders the results by project_memberships count.
func ByProjectMembershipsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProjectMembershipsStep(), opts...)
	}
}

// ByProjectMemberships orders the results by project_memberships terms.
func ByProjectMemberships(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectMembershipsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProjectMembershipsGrantedCount orders the results by project_memberships_granted count.
func ByProjectMembershipsGrantedCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProjectMembershipsGrantedStep(), opts...)
	}
}

// ByProjectMembershipsGranted orders the results by project_memberships_granted terms.
func ByProjectMembershipsGranted(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectMembershipsGrantedStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTasksAssignedCount orders the results by tasks_assigned count.
func ByTasksAssignedCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTasksAssignedStep(), opts...)
	}
}

// ByTasksAssigned orders the results by tasks_assigned terms.
func ByTasksAssigned(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTasksAssignedStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTaskAssigneesCount orders the results by task_assignees count.
func ByTaskAssigneesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTaskAssigneesStep(), opts...)
	}
}

// ByTaskAssignees orders the results by task_assignees terms.
func ByTaskAssignees(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskAssigneesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySprintsCount orders the results by sprints count.
func BySprintsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSprintsStep(), opts...)
	}
}

// BySprints orders the results by sprints terms.
func BySprints(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSprintsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTagsCount orders the results by tags count.
func ByTagsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTagsStep(), opts...)
	}
}

// ByTags orders the results by tags terms.
func ByTags(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTagsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAPIKeysCount orders the results by api_keys count.
func ByAPIKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAPIKeysStep(), opts...)
	}
}

// ByAPIKeys orders the results by api_keys terms.
func ByAPIKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserActivitiesCount orders the results by user_activities count.
func ByUserActivitiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserActivitiesStep(), opts...)
	}
}

// ByUserActivities orders the results by user_activities terms.
func ByUserActivities(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserActivitiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTaskCommentsCount orders the results by task_comments count.
func ByTaskCommentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTaskCommentsStep(), opts...)
	}
}

// ByTaskComments orders the results by task_comments terms.
func ByTaskComments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskCommentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInvitesSentCount orders the results by invites_sent count.
func ByInvitesSentCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInvitesSentStep(), opts...)
	}
}

// ByInvitesSent orders the results by invites_sent terms.
func ByInvitesSent(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInvitesSentStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInvitesReceivedCount orders the results by invites_received count.
func ByInvitesReceivedCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInvitesReceivedStep(), opts...)
	}
}

// ByInvitesReceived orders the results by invites_received terms.
func ByInvitesReceived(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInvitesReceivedStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTeamInvitationsSentCount orders the results by team_invitations_sent count.
func ByTeamInvitationsSentCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeamInvitationsSentStep(), opts...)
	}
}

// ByTeamInvitationsSent orders the results by team_invitations_sent terms.
func ByTeamInvitationsSent(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamInvitationsSentStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTeamInvitationsReceivedCount orders the results by team_invitations_received count.
func ByTeamInvitationsReceivedCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeamInvitationsReceivedStep(), opts...)
	}
}

// ByTeamInvitationsReceived orders the results by team_invitations_received terms.
func ByTeamInvitationsReceived(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamInvitationsReceivedStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCloudinaryCredentialsCount orders the results by cloudinary_credentials count.
func ByCloudinaryCredentialsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCloudinaryCredentialsStep(), opts...)
	}
}

// ByCloudinaryCredentials orders the results by cloudinary_credentials terms.
func ByCloudinaryCredentials(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCloudinaryCredentialsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTaskAttachmentsCount orders the results by task_attachments count.
func ByTaskAttachmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTaskAttachmentsStep(), opts...)
	}
}

// ByTaskAttachments orders the results by task_attachments terms.
func ByTaskAttachments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskAttachmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWikiPagesCreatedCount orders the results by wiki_pages_created count.
func ByWikiPagesCreatedCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWikiPagesCreatedStep(), opts...)
	}
}

// ByWikiPagesCreated orders the results by wiki_pages_created terms.
func ByWikiPagesCreated(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWikiPagesCreatedStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByYjsUpdatesCount orders the results by yjs_updates count.
func ByYjsUpdatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newYjsUpdatesStep(), opts...)
	}
}

// ByYjsUpdates orders the results by yjs_updates terms.
func ByYjsUpdates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newYjsUpdatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnedProjectsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnedProjectsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OwnedProjectsTable, OwnedProjectsColumn),
	)
}
func newOwnedTeamsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnedTeamsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OwnedTeamsTable, OwnedTeamsColumn),
	)
}
func newTeamMembershipsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamMembershipsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TeamMembershipsTable, TeamMembershipsColumn),
	)
}
func newProjectMembershipsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectMembershipsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProjectMembershipsTable, ProjectMembershipsColumn),
	)
}
func newProjectMembershipsGrantedStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectMembershipsGrantedInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProjectMembershipsGrantedTable, ProjectMembershipsGrantedColumn),
	)
}
func newTasksAssignedStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TasksAssignedInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TasksAssignedTable, TasksAssignedColumn),
	)
}
func newTaskAssigneesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskAssigneesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TaskAssigneesTable, TaskAssigneesColumn),
	)
}
func newSprintsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SprintsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SprintsTable, SprintsColumn),
	)
}
func newTagsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TagsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TagsTable, TagsColumn),
	)
}
func newAPIKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
	)
}
func newUserActivitiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserActivitiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserActivitiesTable, UserActivitiesColumn),
	)
}
func newTaskCommentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskCommentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TaskCommentsTable, TaskCommentsColumn),
	)
}
func newInvitesSentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InvitesSentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InvitesSentTable, InvitesSentColumn),
	)
}
func newInvitesReceivedStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InvitesReceivedInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InvitesReceivedTable, InvitesReceivedColumn),
	)
}
func newTeamInvitationsSentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamInvitationsSentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TeamInvitationsSentTable, TeamInvitationsSentColumn),
	)
}
func newTeamInvitationsReceivedStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamInvitationsReceivedInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TeamInvitationsReceivedTable, TeamInvitationsReceivedColumn),
	)
}
func newCloudinaryCredentialsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CloudinaryCredentialsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CloudinaryCredentialsTable, CloudinaryCredentialsColumn),
	)
}
func newTaskAttachmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskAttachmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TaskAttachmentsTable, TaskAttachmentsColumn),
	)
}
func newWikiPagesCreatedStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WikiPagesCreatedInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, WikiPagesCreatedTable, WikiPagesCreatedColumn),
	)
}
func newYjsUpdatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(YjsUpdatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, YjsUpdatesTable, YjsUpdatesColumn),
	)
}
