// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"taskai/ent/task"
	"taskai/ent/taskassignee"
	"taskai/ent/user"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TaskAssignee is the model entity for the TaskAssignee schema.
type TaskAssignee struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID int64 `json:"task_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskAssigneeQuery when eager-loading is set.
	Edges        TaskAssigneeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskAssigneeEdges holds the relations/edges for other nodes in the graph.
type TaskAssigneeEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskAssigneeEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskAssigneeEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskAssignee) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case taskassignee.FieldID, taskassignee.FieldTaskID, taskassignee.FieldUserID:
			values[i] = new(sql.NullInt64)
		case taskassignee.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskAssignee fields.
func (_m *TaskAssignee) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case taskassignee.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case taskassignee.FieldTaskID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.Int64
			}
		case taskassignee.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case taskassignee.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskAssignee.
// This includes values selected through modifiers, order, etc.
func (_m *TaskAssignee) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the TaskAssignee entity.
func (_m *TaskAssignee) QueryTask() *TaskQuery {
	return NewTaskAssigneeClient(_m.config).QueryTask(_m)
}

// QueryUser queries the "user" edge of the TaskAssignee entity.
func (_m *TaskAssignee) QueryUser() *UserQuery {
	return NewTaskAssigneeClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this TaskAssignee.
// Note that you need to call TaskAssignee.Unwrap() before calling this method if this TaskAssignee
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TaskAssignee) Update() *TaskAssigneeUpdateOne {
	return NewTaskAssigneeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TaskAssignee entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TaskAssignee) Unwrap() *TaskAssignee {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskAssignee is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TaskAssignee) String() string {
	var builder strings.Builder
	builder.WriteString("TaskAssignee(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TaskAssignees is a parsable slice of TaskAssignee.
type TaskAssignees []*TaskAssignee
