// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/predicate"
	"taskai/ent/project"
	"taskai/ent/sprint"
	"taskai/ent/swimlane"
	"taskai/ent/task"
	"taskai/ent/taskassignee"
	"taskai/ent/taskattachment"
	"taskai/ent/taskcomment"
	"taskai/ent/tasktag"
	"taskai/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *TaskUpdate) SetProjectID(v int64) *TaskUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableProjectID(v *int64) *TaskUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetTaskNumber sets the "task_number" field.
func (_u *TaskUpdate) SetTaskNumber(v int) *TaskUpdate {
	_u.mutation.ResetTaskNumber()
	_u.mutation.SetTaskNumber(v)
	return _u
}

// SetNillableTaskNumber sets the "task_number" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableTaskNumber(v *int) *TaskUpdate {
	if v != nil {
		_u.SetTaskNumber(*v)
	}
	return _u
}

// AddTaskNumber adds value to the "task_number" field.
func (_u *TaskUpdate) AddTaskNumber(v int) *TaskUpdate {
	_u.mutation.AddTaskNumber(v)
	return _u
}

// ClearTaskNumber clears the value of the "task_number" field.
func (_u *TaskUpdate) ClearTaskNumber() *TaskUpdate {
	_u.mutation.ClearTaskNumber()
	return _u
}

// SetTitle sets the "title" field.
func (_u *TaskUpdate) SetTitle(v string) *TaskUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableTitle(v *string) *TaskUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdate) SetDescription(v string) *TaskUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableDescription(v *string) *TaskUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdate) ClearDescription() *TaskUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdate) SetStatus(v string) *TaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableStatus(v *string) *TaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSwimLaneID sets the "swim_lane_id" field.
func (_u *TaskUpdate) SetSwimLaneID(v int64) *TaskUpdate {
	_u.mutation.SetSwimLaneID(v)
	return _u
}

// SetNillableSwimLaneID sets the "swim_lane_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableSwimLaneID(v *int64) *TaskUpdate {
	if v != nil {
		_u.SetSwimLaneID(*v)
	}
	return _u
}

// ClearSwimLaneID clears the value of the "swim_lane_id" field.
func (_u *TaskUpdate) ClearSwimLaneID() *TaskUpdate {
	_u.mutation.ClearSwimLaneID()
	return _u
}

// SetSprintID sets the "sprint_id" field.
func (_u *TaskUpdate) SetSprintID(v int64) *TaskUpdate {
	_u.mutation.SetSprintID(v)
	return _u
}

// SetNillableSprintID sets the "sprint_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableSprintID(v *int64) *TaskUpdate {
	if v != nil {
		_u.SetSprintID(*v)
	}
	return _u
}

// ClearSprintID clears the value of the "sprint_id" field.
func (_u *TaskUpdate) ClearSprintID() *TaskUpdate {
	_u.mutation.ClearSprintID()
	return _u
}

// SetAssigneeID sets the "assignee_id" field.
func (_u *TaskUpdate) SetAssigneeID(v int64) *TaskUpdate {
	_u.mutation.SetAssigneeID(v)
	return _u
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableAssigneeID(v *int64) *TaskUpdate {
	if v != nil {
		_u.SetAssigneeID(*v)
	}
	return _u
}

// ClearAssigneeID clears the value of the "assignee_id" field.
func (_u *TaskUpdate) ClearAssigneeID() *TaskUpdate {
	_u.mutation.ClearAssigneeID()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdate) SetPriority(v string) *TaskUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdate) SetNillablePriority(v *string) *TaskUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetEstimatedHours sets the "estimated_hours" field.
func (_u *TaskUpdate) SetEstimatedHours(v float64) *TaskUpdate {
	_u.mutation.ResetEstimatedHours()
	_u.mutation.SetEstimatedHours(v)
	return _u
}

// SetNillableEstimatedHours sets the "estimated_hours" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableEstimatedHours(v *float64) *TaskUpdate {
	if v != nil {
		_u.SetEstimatedHours(*v)
	}
	return _u
}

// AddEstimatedHours adds value to the "estimated_hours" field.
func (_u *TaskUpdate) AddEstimatedHours(v float64) *TaskUpdate {
	_u.mutation.AddEstimatedHours(v)
	return _u
}

// ClearEstimatedHours clears the value of the "estimated_hours" field.
func (_u *TaskUpdate) ClearEstimatedHours() *TaskUpdate {
	_u.mutation.ClearEstimatedHours()
	return _u
}

// SetActualHours sets the "actual_hours" field.
func (_u *TaskUpdate) SetActualHours(v float64) *TaskUpdate {
	_u.mutation.ResetActualHours()
	_u.mutation.SetActualHours(v)
	return _u
}

// SetNillableActualHours sets the "actual_hours" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableActualHours(v *float64) *TaskUpdate {
	if v != nil {
		_u.SetActualHours(*v)
	}
	return _u
}

// AddActualHours adds value to the "actual_hours" field.
func (_u *TaskUpdate) AddActualHours(v float64) *TaskUpdate {
	_u.mutation.AddActualHours(v)
	return _u
}

// ClearActualHours clears the value of the "actual_hours" field.
func (_u *TaskUpdate) ClearActualHours() *TaskUpdate {
	_u.mutation.ClearActualHours()
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *TaskUpdate) SetDueDate(v time.Time) *TaskUpdate {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *TaskUpdate) SetNillableDueDate(v *time.Time) *TaskUpdate {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *TaskUpdate) ClearDueDate() *TaskUpdate {
	_u.mutation.ClearDueDate()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdate) SetUpdatedAt(v time.Time) *TaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TaskUpdate) SetProject(v *Project) *TaskUpdate {
	return _u.SetProjectID(v.ID)
}

// SetSwimLane sets the "swim_lane" edge to the SwimLane entity.
func (_u *TaskUpdate) SetSwimLane(v *SwimLane) *TaskUpdate {
	return _u.SetSwimLaneID(v.ID)
}

// SetSprint sets the "sprint" edge to the Sprint entity.
func (_u *TaskUpdate) SetSprint(v *Sprint) *TaskUpdate {
	return _u.SetSprintID(v.ID)
}

// SetAssignee sets the "assignee" edge to the User entity.
func (_u *TaskUpdate) SetAssignee(v *User) *TaskUpdate {
	return _u.SetAssigneeID(v.ID)
}

// AddCommentIDs adds the "comments" edge to the TaskComment entity by IDs.
func (_u *TaskUpdate) AddCommentIDs(ids ...int64) *TaskUpdate {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the TaskComment entity.
func (_u *TaskUpdate) AddComments(v ...*TaskComment) *TaskUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the TaskAttachment entity by IDs.
func (_u *TaskUpdate) AddAttachmentIDs(ids ...int64) *TaskUpdate {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the TaskAttachment entity.
func (_u *TaskUpdate) AddAttachments(v ...*TaskAttachment) *TaskUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// AddTaskTagIDs adds the "task_tags" edge to the TaskTag entity by IDs.
func (_u *TaskUpdate) AddTaskTagIDs(ids ...int) *TaskUpdate {
	_u.mutation.AddTaskTagIDs(ids...)
	return _u
}

// AddTaskTags adds the "task_tags" edges to the TaskTag entity.
func (_u *TaskUpdate) AddTaskTags(v ...*TaskTag) *TaskUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskTagIDs(ids...)
}

// AddTaskAssigneeIDs adds the "task_assignees" edge to the TaskAssignee entity by IDs.
func (_u *TaskUpdate) AddTaskAssigneeIDs(ids ...int) *TaskUpdate {
	_u.mutation.AddTaskAssigneeIDs(ids...)
	return _u
}

// AddTaskAssignees adds the "task_assignees" edges to the TaskAssignee entity.
func (_u *TaskUpdate) AddTaskAssignees(v ...*TaskAssignee) *TaskUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskAssigneeIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdate) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TaskUpdate) ClearProject() *TaskUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearSwimLane clears the "swim_lane" edge to the SwimLane entity.
func (_u *TaskUpdate) ClearSwimLane() *TaskUpdate {
	_u.mutation.ClearSwimLane()
	return _u
}

// ClearSprint clears the "sprint" edge to the Sprint entity.
func (_u *TaskUpdate) ClearSprint() *TaskUpdate {
	_u.mutation.ClearSprint()
	return _u
}

// ClearAssignee clears the "assignee" edge to the User entity.
func (_u *TaskUpdate) ClearAssignee() *TaskUpdate {
	_u.mutation.ClearAssignee()
	return _u
}

// ClearComments clears all "comments" edges to the TaskComment entity.
func (_u *TaskUpdate) ClearComments() *TaskUpdate {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to TaskComment entities by IDs.
func (_u *TaskUpdate) RemoveCommentIDs(ids ...int64) *TaskUpdate {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to TaskComment entities.
func (_u *TaskUpdate) RemoveComments(v ...*TaskComment) *TaskUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the TaskAttachment entity.
func (_u *TaskUpdate) ClearAttachments() *TaskUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to TaskAttachment entities by IDs.
func (_u *TaskUpdate) RemoveAttachmentIDs(ids ...int64) *TaskUpdate {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to TaskAttachment entities.
func (_u *TaskUpdate) RemoveAttachments(v ...*TaskAttachment) *TaskUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// ClearTaskTags clears all "task_tags" edges to the TaskTag entity.
func (_u *TaskUpdate) ClearTaskTags() *TaskUpdate {
	_u.mutation.ClearTaskTags()
	return _u
}

// RemoveTaskTagIDs removes the "task_tags" edge to TaskTag entities by IDs.
func (_u *TaskUpdate) RemoveTaskTagIDs(ids ...int) *TaskUpdate {
	_u.mutation.RemoveTaskTagIDs(ids...)
	return _u
}

// RemoveTaskTags removes "task_tags" edges to TaskTag entities.
func (_u *TaskUpdate) RemoveTaskTags(v ...*TaskTag) *TaskUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskTagIDs(ids...)
}

// ClearTaskAssignees clears all "task_assignees" edges to the TaskAssignee entity.
func (_u *TaskUpdate) ClearTaskAssignees() *TaskUpdate {
	_u.mutation.ClearTaskAssignees()
	return _u
}

// RemoveTaskAssigneeIDs removes the "task_assignees" edge to TaskAssignee entities by IDs.
func (_u *TaskUpdate) RemoveTaskAssigneeIDs(ids ...int) *TaskUpdate {
	_u.mutation.RemoveTaskAssigneeIDs(ids...)
	return _u
}

// RemoveTaskAssignees removes "task_assignees" edges to TaskAssignee entities.
func (_u *TaskUpdate) RemoveTaskAssignees(v ...*TaskAssignee) *TaskUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskAssigneeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := task.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Task.title": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.project"`)
	}
	return nil
}

func (_u *TaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskNumber(); ok {
		_spec.SetField(task.FieldTaskNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTaskNumber(); ok {
		_spec.AddField(task.FieldTaskNumber, field.TypeInt, value)
	}
	if _u.mutation.TaskNumberCleared() {
		_spec.ClearField(task.FieldTaskNumber, field.TypeInt)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.EstimatedHours(); ok {
		_spec.SetField(task.FieldEstimatedHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedHours(); ok {
		_spec.AddField(task.FieldEstimatedHours, field.TypeFloat64, value)
	}
	if _u.mutation.EstimatedHoursCleared() {
		_spec.ClearField(task.FieldEstimatedHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ActualHours(); ok {
		_spec.SetField(task.FieldActualHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualHours(); ok {
		_spec.AddField(task.FieldActualHours, field.TypeFloat64, value)
	}
	if _u.mutation.ActualHoursCleared() {
		_spec.ClearField(task.FieldActualHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(task.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(task.FieldDueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SwimLaneCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.SwimLaneTable,
			Columns: []string{task.SwimLaneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(swimlane.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SwimLaneIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.SwimLaneTable,
			Columns: []string{task.SwimLaneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(swimlane.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SprintCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.SprintTable,
			Columns: []string{task.SprintColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sprint.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SprintIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.SprintTable,
			Columns: []string{task.SprintColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sprint.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssigneeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.AssigneeTable,
			Columns: []string{task.AssigneeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssigneeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.AssigneeTable,
			Columns: []string{task.AssigneeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcomment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskattachment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TaskTagsTable,
			Columns: []string{task.TaskTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskTagsIDs(); len(nodes) > 0 && !_u.mutation.TaskTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TaskTagsTable,
			Columns: []string{task.TaskTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TaskTagsTable,
			Columns: []string{task.TaskTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskAssigneesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TaskAssigneesTable,
			Columns: []string{task.TaskAssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskAssigneesIDs(); len(nodes) > 0 && !_u.mutation.TaskAssigneesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TaskAssigneesTable,
			Columns: []string{task.TaskAssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskAssigneesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TaskAssigneesTable,
			Columns: []string{task.TaskAssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetProjectID sets the "project_id" field.
func (_u *TaskUpdateOne) SetProjectID(v int64) *TaskUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableProjectID(v *int64) *TaskUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetTaskNumber sets the "task_number" field.
func (_u *TaskUpdateOne) SetTaskNumber(v int) *TaskUpdateOne {
	_u.mutation.ResetTaskNumber()
	_u.mutation.SetTaskNumber(v)
	return _u
}

// SetNillableTaskNumber sets the "task_number" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableTaskNumber(v *int) *TaskUpdateOne {
	if v != nil {
		_u.SetTaskNumber(*v)
	}
	return _u
}

// AddTaskNumber adds value to the "task_number" field.
func (_u *TaskUpdateOne) AddTaskNumber(v int) *TaskUpdateOne {
	_u.mutation.AddTaskNumber(v)
	return _u
}

// ClearTaskNumber clears the value of the "task_number" field.
func (_u *TaskUpdateOne) ClearTaskNumber() *TaskUpdateOne {
	_u.mutation.ClearTaskNumber()
	return _u
}

// SetTitle sets the "title" field.
func (_u *TaskUpdateOne) SetTitle(v string) *TaskUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableTitle(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskUpdateOne) SetDescription(v string) *TaskUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableDescription(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskUpdateOne) ClearDescription() *TaskUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskUpdateOne) SetStatus(v string) *TaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableStatus(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSwimLaneID sets the "swim_lane_id" field.
func (_u *TaskUpdateOne) SetSwimLaneID(v int64) *TaskUpdateOne {
	_u.mutation.SetSwimLaneID(v)
	return _u
}

// SetNillableSwimLaneID sets the "swim_lane_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableSwimLaneID(v *int64) *TaskUpdateOne {
	if v != nil {
		_u.SetSwimLaneID(*v)
	}
	return _u
}

// ClearSwimLaneID clears the value of the "swim_lane_id" field.
func (_u *TaskUpdateOne) ClearSwimLaneID() *TaskUpdateOne {
	_u.mutation.ClearSwimLaneID()
	return _u
}

// SetSprintID sets the "sprint_id" field.
func (_u *TaskUpdateOne) SetSprintID(v int64) *TaskUpdateOne {
	_u.mutation.SetSprintID(v)
	return _u
}

// SetNillableSprintID sets the "sprint_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableSprintID(v *int64) *TaskUpdateOne {
	if v != nil {
		_u.SetSprintID(*v)
	}
	return _u
}

// ClearSprintID clears the value of the "sprint_id" field.
func (_u *TaskUpdateOne) ClearSprintID() *TaskUpdateOne {
	_u.mutation.ClearSprintID()
	return _u
}

// SetAssigneeID sets the "assignee_id" field.
func (_u *TaskUpdateOne) SetAssigneeID(v int64) *TaskUpdateOne {
	_u.mutation.SetAssigneeID(v)
	return _u
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableAssigneeID(v *int64) *TaskUpdateOne {
	if v != nil {
		_u.SetAssigneeID(*v)
	}
	return _u
}

// ClearAssigneeID clears the value of the "assignee_id" field.
func (_u *TaskUpdateOne) ClearAssigneeID() *TaskUpdateOne {
	_u.mutation.ClearAssigneeID()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskUpdateOne) SetPriority(v string) *TaskUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillablePriority(v *string) *TaskUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetEstimatedHours sets the "estimated_hours" field.
func (_u *TaskUpdateOne) SetEstimatedHours(v float64) *TaskUpdateOne {
	_u.mutation.ResetEstimatedHours()
	_u.mutation.SetEstimatedHours(v)
	return _u
}

// SetNillableEstimatedHours sets the "estimated_hours" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableEstimatedHours(v *float64) *TaskUpdateOne {
	if v != nil {
		_u.SetEstimatedHours(*v)
	}
	return _u
}

// AddEstimatedHours adds value to the "estimated_hours" field.
func (_u *TaskUpdateOne) AddEstimatedHours(v float64) *TaskUpdateOne {
	_u.mutation.AddEstimatedHours(v)
	return _u
}

// ClearEstimatedHours clears the value of the "estimated_hours" field.
func (_u *TaskUpdateOne) ClearEstimatedHours() *TaskUpdateOne {
	_u.mutation.ClearEstimatedHours()
	return _u
}

// SetActualHours sets the "actual_hours" field.
func (_u *TaskUpdateOne) SetActualHours(v float64) *TaskUpdateOne {
	_u.mutation.ResetActualHours()
	_u.mutation.SetActualHours(v)
	return _u
}

// SetNillableActualHours sets the "actual_hours" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableActualHours(v *float64) *TaskUpdateOne {
	if v != nil {
		_u.SetActualHours(*v)
	}
	return _u
}

// AddActualHours adds value to the "actual_hours" field.
func (_u *TaskUpdateOne) AddActualHours(v float64) *TaskUpdateOne {
	_u.mutation.AddActualHours(v)
	return _u
}

// ClearActualHours clears the value of the "actual_hours" field.
func (_u *TaskUpdateOne) ClearActualHours() *TaskUpdateOne {
	_u.mutation.ClearActualHours()
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *TaskUpdateOne) SetDueDate(v time.Time) *TaskUpdateOne {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *TaskUpdateOne) SetNillableDueDate(v *time.Time) *TaskUpdateOne {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *TaskUpdateOne) ClearDueDate() *TaskUpdateOne {
	_u.mutation.ClearDueDate()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskUpdateOne) SetUpdatedAt(v time.Time) *TaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *TaskUpdateOne) SetProject(v *Project) *TaskUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetSwimLane sets the "swim_lane" edge to the SwimLane entity.
func (_u *TaskUpdateOne) SetSwimLane(v *SwimLane) *TaskUpdateOne {
	return _u.SetSwimLaneID(v.ID)
}

// SetSprint sets the "sprint" edge to the Sprint entity.
func (_u *TaskUpdateOne) SetSprint(v *Sprint) *TaskUpdateOne {
	return _u.SetSprintID(v.ID)
}

// SetAssignee sets the "assignee" edge to the User entity.
func (_u *TaskUpdateOne) SetAssignee(v *User) *TaskUpdateOne {
	return _u.SetAssigneeID(v.ID)
}

// AddCommentIDs adds the "comments" edge to the TaskComment entity by IDs.
func (_u *TaskUpdateOne) AddCommentIDs(ids ...int64) *TaskUpdateOne {
	_u.mutation.AddCommentIDs(ids...)
	return _u
}

// AddComments adds the "comments" edges to the TaskComment entity.
func (_u *TaskUpdateOne) AddComments(v ...*TaskComment) *TaskUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommentIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the TaskAttachment entity by IDs.
func (_u *TaskUpdateOne) AddAttachmentIDs(ids ...int64) *TaskUpdateOne {
	_u.mutation.AddAttachmentIDs(ids...)
	return _u
}

// AddAttachments adds the "attachments" edges to the TaskAttachment entity.
func (_u *TaskUpdateOne) AddAttachments(v ...*TaskAttachment) *TaskUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAttachmentIDs(ids...)
}

// AddTaskTagIDs adds the "task_tags" edge to the TaskTag entity by IDs.
func (_u *TaskUpdateOne) AddTaskTagIDs(ids ...int) *TaskUpdateOne {
	_u.mutation.AddTaskTagIDs(ids...)
	return _u
}

// AddTaskTags adds the "task_tags" edges to the TaskTag entity.
func (_u *TaskUpdateOne) AddTaskTags(v ...*TaskTag) *TaskUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskTagIDs(ids...)
}

// AddTaskAssigneeIDs adds the "task_assignees" edge to the TaskAssignee entity by IDs.
func (_u *TaskUpdateOne) AddTaskAssigneeIDs(ids ...int) *TaskUpdateOne {
	_u.mutation.AddTaskAssigneeIDs(ids...)
	return _u
}

// AddTaskAssignees adds the "task_assignees" edges to the TaskAssignee entity.
func (_u *TaskUpdateOne) AddTaskAssignees(v ...*TaskAssignee) *TaskUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskAssigneeIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (_u *TaskUpdateOne) Mutation() *TaskMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *TaskUpdateOne) ClearProject() *TaskUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearSwimLane clears the "swim_lane" edge to the SwimLane entity.
func (_u *TaskUpdateOne) ClearSwimLane() *TaskUpdateOne {
	_u.mutation.ClearSwimLane()
	return _u
}

// ClearSprint clears the "sprint" edge to the Sprint entity.
func (_u *TaskUpdateOne) ClearSprint() *TaskUpdateOne {
	_u.mutation.ClearSprint()
	return _u
}

// ClearAssignee clears the "assignee" edge to the User entity.
func (_u *TaskUpdateOne) ClearAssignee() *TaskUpdateOne {
	_u.mutation.ClearAssignee()
	return _u
}

// ClearComments clears all "comments" edges to the TaskComment entity.
func (_u *TaskUpdateOne) ClearComments() *TaskUpdateOne {
	_u.mutation.ClearComments()
	return _u
}

// RemoveCommentIDs removes the "comments" edge to TaskComment entities by IDs.
func (_u *TaskUpdateOne) RemoveCommentIDs(ids ...int64) *TaskUpdateOne {
	_u.mutation.RemoveCommentIDs(ids...)
	return _u
}

// RemoveComments removes "comments" edges to TaskComment entities.
func (_u *TaskUpdateOne) RemoveComments(v ...*TaskComment) *TaskUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommentIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the TaskAttachment entity.
func (_u *TaskUpdateOne) ClearAttachments() *TaskUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// RemoveAttachmentIDs removes the "attachments" edge to TaskAttachment entities by IDs.
func (_u *TaskUpdateOne) RemoveAttachmentIDs(ids ...int64) *TaskUpdateOne {
	_u.mutation.RemoveAttachmentIDs(ids...)
	return _u
}

// RemoveAttachments removes "attachments" edges to TaskAttachment entities.
func (_u *TaskUpdateOne) RemoveAttachments(v ...*TaskAttachment) *TaskUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAttachmentIDs(ids...)
}

// ClearTaskTags clears all "task_tags" edges to the TaskTag entity.
func (_u *TaskUpdateOne) ClearTaskTags() *TaskUpdateOne {
	_u.mutation.ClearTaskTags()
	return _u
}

// RemoveTaskTagIDs removes the "task_tags" edge to TaskTag entities by IDs.
func (_u *TaskUpdateOne) RemoveTaskTagIDs(ids ...int) *TaskUpdateOne {
	_u.mutation.RemoveTaskTagIDs(ids...)
	return _u
}

// RemoveTaskTags removes "task_tags" edges to TaskTag entities.
func (_u *TaskUpdateOne) RemoveTaskTags(v ...*TaskTag) *TaskUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskTagIDs(ids...)
}

// ClearTaskAssignees clears all "task_assignees" edges to the TaskAssignee entity.
func (_u *TaskUpdateOne) ClearTaskAssignees() *TaskUpdateOne {
	_u.mutation.ClearTaskAssignees()
	return _u
}

// RemoveTaskAssigneeIDs removes the "task_assignees" edge to TaskAssignee entities by IDs.
func (_u *TaskUpdateOne) RemoveTaskAssigneeIDs(ids ...int) *TaskUpdateOne {
	_u.mutation.RemoveTaskAssigneeIDs(ids...)
	return _u
}

// RemoveTaskAssignees removes "task_assignees" edges to TaskAssignee entities.
func (_u *TaskUpdateOne) RemoveTaskAssignees(v ...*TaskAssignee) *TaskUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskAssigneeIDs(ids...)
}

// Where appends a list predicates to the TaskUpdate builder.
func (_u *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Task entity.
func (_u *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := task.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Task.title": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Task.project"`)
	}
	return nil
}

func (_u *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskNumber(); ok {
		_spec.SetField(task.FieldTaskNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTaskNumber(); ok {
		_spec.AddField(task.FieldTaskNumber, field.TypeInt, value)
	}
	if _u.mutation.TaskNumberCleared() {
		_spec.ClearField(task.FieldTaskNumber, field.TypeInt)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.EstimatedHours(); ok {
		_spec.SetField(task.FieldEstimatedHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedEstimatedHours(); ok {
		_spec.AddField(task.FieldEstimatedHours, field.TypeFloat64, value)
	}
	if _u.mutation.EstimatedHoursCleared() {
		_spec.ClearField(task.FieldEstimatedHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ActualHours(); ok {
		_spec.SetField(task.FieldActualHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualHours(); ok {
		_spec.AddField(task.FieldActualHours, field.TypeFloat64, value)
	}
	if _u.mutation.ActualHoursCleared() {
		_spec.ClearField(task.FieldActualHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(task.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(task.FieldDueDate, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SwimLaneCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.SwimLaneTable,
			Columns: []string{task.SwimLaneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(swimlane.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SwimLaneIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.SwimLaneTable,
			Columns: []string{task.SwimLaneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(swimlane.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SprintCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.SprintTable,
			Columns: []string{task.SprintColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sprint.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SprintIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.SprintTable,
			Columns: []string{task.SprintColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sprint.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssigneeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.AssigneeTable,
			Columns: []string{task.AssigneeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssigneeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.AssigneeTable,
			Columns: []string{task.AssigneeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcomment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !_u.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskattachment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !_u.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TaskTagsTable,
			Columns: []string{task.TaskTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskTagsIDs(); len(nodes) > 0 && !_u.mutation.TaskTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TaskTagsTable,
			Columns: []string{task.TaskTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TaskTagsTable,
			Columns: []string{task.TaskTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tasktag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskAssigneesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TaskAssigneesTable,
			Columns: []string{task.TaskAssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskAssigneesIDs(); len(nodes) > 0 && !_u.mutation.TaskAssigneesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TaskAssigneesTable,
			Columns: []string{task.TaskAssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskAssigneesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.TaskAssigneesTable,
			Columns: []string{task.TaskAssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Task{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
