// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"taskai/ent/project"
	"taskai/ent/sprint"
	"taskai/ent/swimlane"
	"taskai/ent/task"
	"taskai/ent/user"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Task is the model entity for the Task schema.
type Task struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID int64 `json:"project_id,omitempty"`
	// TaskNumber holds the value of the "task_number" field.
	TaskNumber *int `json:"task_number,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SwimLaneID holds the value of the "swim_lane_id" field.
	SwimLaneID *int64 `json:"swim_lane_id,omitempty"`
	// SprintID holds the value of the "sprint_id" field.
	SprintID *int64 `json:"sprint_id,omitempty"`
	// AssigneeID holds the value of the "assignee_id" field.
	AssigneeID *int64 `json:"assignee_id,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority string `json:"priority,omitempty"`
	// EstimatedHours holds the value of the "estimated_hours" field.
	EstimatedHours *float64 `json:"estimated_hours,omitempty"`
	// ActualHours holds the value of the "actual_hours" field.
	ActualHours *float64 `json:"actual_hours,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate *time.Time `json:"start_date,omitempty"`
	// DueDate holds the value of the "due_date" field.
	DueDate *time.Time `json:"due_date,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskQuery when eager-loading is set.
	Edges        TaskEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskEdges holds the relations/edges for other nodes in the graph.
type TaskEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// SwimLane holds the value of the swim_lane edge.
	SwimLane *SwimLane `json:"swim_lane,omitempty"`
	// Sprint holds the value of the sprint edge.
	Sprint *Sprint `json:"sprint,omitempty"`
	// Assignee holds the value of the assignee edge.
	Assignee *User `json:"assignee,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*TaskComment `json:"comments,omitempty"`
	// Attachments holds the value of the attachments edge.
	Attachments []*TaskAttachment `json:"attachments,omitempty"`
	// TaskTags holds the value of the task_tags edge.
	TaskTags []*TaskTag `json:"task_tags,omitempty"`
	// TaskAssignees holds the value of the task_assignees edge.
	TaskAssignees []*TaskAssignee `json:"task_assignees,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// SwimLaneOrErr returns the SwimLane value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) SwimLaneOrErr() (*SwimLane, error) {
	if e.SwimLane != nil {
		return e.SwimLane, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: swimlane.Label}
	}
	return nil, &NotLoadedError{edge: "swim_lane"}
}

// SprintOrErr returns the Sprint value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) SprintOrErr() (*Sprint, error) {
	if e.Sprint != nil {
		return e.Sprint, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: sprint.Label}
	}
	return nil, &NotLoadedError{edge: "sprint"}
}

// AssigneeOrErr returns the Assignee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) AssigneeOrErr() (*User, error) {
	if e.Assignee != nil {
		return e.Assignee, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "assignee"}
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) CommentsOrErr() ([]*TaskComment, error) {
	if e.loadedTypes[4] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) AttachmentsOrErr() ([]*TaskAttachment, error) {
	if e.loadedTypes[5] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// TaskTagsOrErr returns the TaskTags value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) TaskTagsOrErr() ([]*TaskTag, error) {
	if e.loadedTypes[6] {
		return e.TaskTags, nil
	}
	return nil, &NotLoadedError{edge: "task_tags"}
}

// TaskAssigneesOrErr returns the TaskAssignees value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) TaskAssigneesOrErr() ([]*TaskAssignee, error) {
	if e.loadedTypes[7] {
		return e.TaskAssignees, nil
	}
	return nil, &NotLoadedError{edge: "task_assignees"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Task) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case task.FieldEstimatedHours, task.FieldActualHours:
			values[i] = new(sql.NullFloat64)
		case task.FieldID, task.FieldProjectID, task.FieldTaskNumber, task.FieldSwimLaneID, task.FieldSprintID, task.FieldAssigneeID:
			values[i] = new(sql.NullInt64)
		case task.FieldTitle, task.FieldDescription, task.FieldStatus, task.FieldPriority:
			values[i] = new(sql.NullString)
		case task.FieldStartDate, task.FieldDueDate, task.FieldCreatedAt, task.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Task fields.
func (_m *Task) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case task.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case task.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = value.Int64
			}
		case task.FieldTaskNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field task_number", values[i])
			} else if value.Valid {
				_m.TaskNumber = new(int)
				*_m.TaskNumber = int(value.Int64)
			}
		case task.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case task.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case task.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case task.FieldSwimLaneID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field swim_lane_id", values[i])
			} else if value.Valid {
				_m.SwimLaneID = new(int64)
				*_m.SwimLaneID = value.Int64
			}
		case task.FieldSprintID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sprint_id", values[i])
			} else if value.Valid {
				_m.SprintID = new(int64)
				*_m.SprintID = value.Int64
			}
		case task.FieldAssigneeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assignee_id", values[i])
			} else if value.Valid {
				_m.AssigneeID = new(int64)
				*_m.AssigneeID = value.Int64
			}
		case task.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = value.String
			}
		case task.FieldEstimatedHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_hours", values[i])
			} else if value.Valid {
				_m.EstimatedHours = new(float64)
				*_m.EstimatedHours = value.Float64
			}
		case task.FieldActualHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_hours", values[i])
			} else if value.Valid {
				_m.ActualHours = new(float64)
				*_m.ActualHours = value.Float64
			}
		case task.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = new(time.Time)
				*_m.StartDate = value.Time
			}
		case task.FieldDueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_date", values[i])
			} else if value.Valid {
				_m.DueDate = new(time.Time)
				*_m.DueDate = value.Time
			}
		case task.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case task.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Task.
// This includes values selected through modifiers, order, etc.
func (_m *Task) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Task entity.
func (_m *Task) QueryProject() *ProjectQuery {
	return NewTaskClient(_m.config).QueryProject(_m)
}

// QuerySwimLane queries the "swim_lane" edge of the Task entity.
func (_m *Task) QuerySwimLane() *SwimLaneQuery {
	return NewTaskClient(_m.config).QuerySwimLane(_m)
}

// QuerySprint queries the "sprint" edge of the Task entity.
func (_m *Task) QuerySprint() *SprintQuery {
	return NewTaskClient(_m.config).QuerySprint(_m)
}

// QueryAssignee queries the "assignee" edge of the Task entity.
func (_m *Task) QueryAssignee() *UserQuery {
	return NewTaskClient(_m.config).QueryAssignee(_m)
}

// QueryComments queries the "comments" edge of the Task entity.
func (_m *Task) QueryComments() *TaskCommentQuery {
	return NewTaskClient(_m.config).QueryComments(_m)
}

// QueryAttachments queries the "attachments" edge of the Task entity.
func (_m *Task) QueryAttachments() *TaskAttachmentQuery {
	return NewTaskClient(_m.config).QueryAttachments(_m)
}

// QueryTaskTags queries the "task_tags" edge of the Task entity.
func (_m *Task) QueryTaskTags() *TaskTagQuery {
	return NewTaskClient(_m.config).QueryTaskTags(_m)
}

// QueryTaskAssignees queries the "task_assignees" edge of the Task entity.
func (_m *Task) QueryTaskAssignees() *TaskAssigneeQuery {
	return NewTaskClient(_m.config).QueryTaskAssignees(_m)
}

// Update returns a builder for updating this Task.
// Note that you need to call Task.Unwrap() before calling this method if this Task
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Task) Update() *TaskUpdateOne {
	return NewTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Task entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Task) Unwrap() *Task {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Task is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Task) String() string {
	var builder strings.Builder
	builder.WriteString("Task(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	if v := _m.TaskNumber; v != nil {
		builder.WriteString("task_number=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.SwimLaneID; v != nil {
		builder.WriteString("swim_lane_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SprintID; v != nil {
		builder.WriteString("sprint_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AssigneeID; v != nil {
		builder.WriteString("assignee_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(_m.Priority)
	builder.WriteString(", ")
	if v := _m.EstimatedHours; v != nil {
		builder.WriteString("estimated_hours=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ActualHours; v != nil {
		builder.WriteString("actual_hours=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.StartDate; v != nil {
		builder.WriteString("start_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DueDate; v != nil {
		builder.WriteString("due_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Tasks is a parsable slice of Task.
type Tasks []*Task
