// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"taskai/ent/user"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"-"`
	// Name holds the value of the "name" field.
	Name *string `json:"name,omitempty"`
	// FirstName holds the value of the "first_name" field.
	FirstName *string `json:"first_name,omitempty"`
	// LastName holds the value of the "last_name" field.
	LastName *string `json:"last_name,omitempty"`
	// IsAdmin holds the value of the "is_admin" field.
	IsAdmin bool `json:"is_admin,omitempty"`
	// TotpSecret holds the value of the "totp_secret" field.
	TotpSecret *string `json:"-"`
	// TotpEnabled holds the value of the "totp_enabled" field.
	TotpEnabled bool `json:"totp_enabled,omitempty"`
	// BackupCodes holds the value of the "backup_codes" field.
	BackupCodes *string `json:"-"`
	// PasswordChangedAt holds the value of the "password_changed_at" field.
	PasswordChangedAt *time.Time `json:"password_changed_at,omitempty"`
	// InviteCount holds the value of the "invite_count" field.
	InviteCount int `json:"invite_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// OwnedProjects holds the value of the owned_projects edge.
	OwnedProjects []*Project `json:"owned_projects,omitempty"`
	// OwnedTeams holds the value of the owned_teams edge.
	OwnedTeams []*Team `json:"owned_teams,omitempty"`
	// TeamMemberships holds the value of the team_memberships edge.
	TeamMemberships []*TeamMember `json:"team_memberships,omitempty"`
	// ProjectMemberships holds the value of the project_memberships edge.
	ProjectMemberships []*ProjectMember `json:"project_memberships,omitempty"`
	// ProjectMembershipsGranted holds the value of the project_memberships_granted edge.
	ProjectMembershipsGranted []*ProjectMember `json:"project_memberships_granted,omitempty"`
	// TasksAssigned holds the value of the tasks_assigned edge.
	TasksAssigned []*Task `json:"tasks_assigned,omitempty"`
	// TaskAssignees holds the value of the task_assignees edge.
	TaskAssignees []*TaskAssignee `json:"task_assignees,omitempty"`
	// Sprints holds the value of the sprints edge.
	Sprints []*Sprint `json:"sprints,omitempty"`
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// UserActivities holds the value of the user_activities edge.
	UserActivities []*UserActivity `json:"user_activities,omitempty"`
	// TaskComments holds the value of the task_comments edge.
	TaskComments []*TaskComment `json:"task_comments,omitempty"`
	// InvitesSent holds the value of the invites_sent edge.
	InvitesSent []*Invite `json:"invites_sent,omitempty"`
	// InvitesReceived holds the value of the invites_received edge.
	InvitesReceived []*Invite `json:"invites_received,omitempty"`
	// TeamInvitationsSent holds the value of the team_invitations_sent edge.
	TeamInvitationsSent []*TeamInvitation `json:"team_invitations_sent,omitempty"`
	// TeamInvitationsReceived holds the value of the team_invitations_received edge.
	TeamInvitationsReceived []*TeamInvitation `json:"team_invitations_received,omitempty"`
	// CloudinaryCredentials holds the value of the cloudinary_credentials edge.
	CloudinaryCredentials []*CloudinaryCredential `json:"cloudinary_credentials,omitempty"`
	// TaskAttachments holds the value of the task_attachments edge.
	TaskAttachments []*TaskAttachment `json:"task_attachments,omitempty"`
	// WikiPagesCreated holds the value of the wiki_pages_created edge.
	WikiPagesCreated []*WikiPage `json:"wiki_pages_created,omitempty"`
	// YjsUpdates holds the value of the yjs_updates edge.
	YjsUpdates []*YjsUpdate `json:"yjs_updates,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [20]bool
}

// OwnedProjectsOrErr returns the OwnedProjects value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) OwnedProjectsOrErr() ([]*Project, error) {
	if e.loadedTypes[0] {
		return e.OwnedProjects, nil
	}
	return nil, &NotLoadedError{edge: "owned_projects"}
}

// OwnedTeamsOrErr returns the OwnedTeams value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) OwnedTeamsOrErr() ([]*Team, error) {
	if e.loadedTypes[1] {
		return e.OwnedTeams, nil
	}
	return nil, &NotLoadedError{edge: "owned_teams"}
}

// TeamMembershipsOrErr returns the TeamMemberships value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TeamMembershipsOrErr() ([]*TeamMember, error) {
	if e.loadedTypes[2] {
		return e.TeamMemberships, nil
	}
	return nil, &NotLoadedError{edge: "team_memberships"}
}

// ProjectMembershipsOrErr returns the ProjectMemberships value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ProjectMembershipsOrErr() ([]*ProjectMember, error) {
	if e.loadedTypes[3] {
		return e.ProjectMemberships, nil
	}
	return nil, &NotLoadedError{edge: "project_memberships"}
}

// ProjectMembershipsGrantedOrErr returns the ProjectMembershipsGranted value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ProjectMembershipsGrantedOrErr() ([]*ProjectMember, error) {
	if e.loadedTypes[4] {
		return e.ProjectMembershipsGranted, nil
	}
	return nil, &NotLoadedError{edge: "project_memberships_granted"}
}

// TasksAssignedOrErr returns the TasksAssigned value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TasksAssignedOrErr() ([]*Task, error) {
	if e.loadedTypes[5] {
		return e.TasksAssigned, nil
	}
	return nil, &NotLoadedError{edge: "tasks_assigned"}
}

// TaskAssigneesOrErr returns the TaskAssignees value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TaskAssigneesOrErr() ([]*TaskAssignee, error) {
	if e.loadedTypes[6] {
		return e.TaskAssignees, nil
	}
	return nil, &NotLoadedError{edge: "task_assignees"}
}

// SprintsOrErr returns the Sprints value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SprintsOrErr() ([]*Sprint, error) {
	if e.loadedTypes[7] {
		return e.Sprints, nil
	}
	return nil, &NotLoadedError{edge: "sprints"}
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[8] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[9] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// UserActivitiesOrErr returns the UserActivities value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UserActivitiesOrErr() ([]*UserActivity, error) {
	if e.loadedTypes[10] {
		return e.UserActivities, nil
	}
	return nil, &NotLoadedError{edge: "user_activities"}
}

// TaskCommentsOrErr returns the TaskComments value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TaskCommentsOrErr() ([]*TaskComment, error) {
	if e.loadedTypes[11] {
		return e.TaskComments, nil
	}
	return nil, &NotLoadedError{edge: "task_comments"}
}

// InvitesSentOrErr returns the InvitesSent value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) InvitesSentOrErr() ([]*Invite, error) {
	if e.loadedTypes[12] {
		return e.InvitesSent, nil
	}
	return nil, &NotLoadedError{edge: "invites_sent"}
}

// InvitesReceivedOrErr returns the InvitesReceived value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) InvitesReceivedOrErr() ([]*Invite, error) {
	if e.loadedTypes[13] {
		return e.InvitesReceived, nil
	}
	return nil, &NotLoadedError{edge: "invites_received"}
}

// TeamInvitationsSentOrErr returns the TeamInvitationsSent value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TeamInvitationsSentOrErr() ([]*TeamInvitation, error) {
	if e.loadedTypes[14] {
		return e.TeamInvitationsSent, nil
	}
	return nil, &NotLoadedError{edge: "team_invitations_sent"}
}

// TeamInvitationsReceivedOrErr returns the TeamInvitationsReceived value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TeamInvitationsReceivedOrErr() ([]*TeamInvitation, error) {
	if e.loadedTypes[15] {
		return e.TeamInvitationsReceived, nil
	}
	return nil, &NotLoadedError{edge: "team_invitations_received"}
}

// CloudinaryCredentialsOrErr returns the CloudinaryCredentials value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CloudinaryCredentialsOrErr() ([]*CloudinaryCredential, error) {
	if e.loadedTypes[16] {
		return e.CloudinaryCredentials, nil
	}
	return nil, &NotLoadedError{edge: "cloudinary_credentials"}
}

// TaskAttachmentsOrErr returns the TaskAttachments value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TaskAttachmentsOrErr() ([]*TaskAttachment, error) {
	if e.loadedTypes[17] {
		return e.TaskAttachments, nil
	}
	return nil, &NotLoadedError{edge: "task_attachments"}
}

// WikiPagesCreatedOrErr returns the WikiPagesCreated value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) WikiPagesCreatedOrErr() ([]*WikiPage, error) {
	if e.loadedTypes[18] {
		return e.WikiPagesCreated, nil
	}
	return nil, &NotLoadedError{edge: "wiki_pages_created"}
}

// YjsUpdatesOrErr returns the YjsUpdates value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) YjsUpdatesOrErr() ([]*YjsUpdate, error) {
	if e.loadedTypes[19] {
		return e.YjsUpdates, nil
	}
	return nil, &NotLoadedError{edge: "yjs_updates"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldIsAdmin, user.FieldTotpEnabled:
			values[i] = new(sql.NullBool)
		case user.FieldID, user.FieldInviteCount:
			values[i] = new(sql.NullInt64)
		case user.FieldEmail, user.FieldPasswordHash, user.FieldName, user.FieldFirstName, user.FieldLastName, user.FieldTotpSecret, user.FieldBackupCodes:
			values[i] = new(sql.NullString)
		case user.FieldPasswordChangedAt, user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case user.FieldFirstName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field first_name", values[i])
			} else if value.Valid {
				_m.FirstName = new(string)
				*_m.FirstName = value.String
			}
		case user.FieldLastName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name", values[i])
			} else if value.Valid {
				_m.LastName = new(string)
				*_m.LastName = value.String
			}
		case user.FieldIsAdmin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_admin", values[i])
			} else if value.Valid {
				_m.IsAdmin = value.Bool
			}
		case user.FieldTotpSecret:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field totp_secret", values[i])
			} else if value.Valid {
				_m.TotpSecret = new(string)
				*_m.TotpSecret = value.String
			}
		case user.FieldTotpEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field totp_enabled", values[i])
			} else if value.Valid {
				_m.TotpEnabled = value.Bool
			}
		case user.FieldBackupCodes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field backup_codes", values[i])
			} else if value.Valid {
				_m.BackupCodes = new(string)
				*_m.BackupCodes = value.String
			}
		case user.FieldPasswordChangedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field password_changed_at", values[i])
			} else if value.Valid {
				_m.PasswordChangedAt = new(time.Time)
				*_m.PasswordChangedAt = value.Time
			}
		case user.FieldInviteCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invite_count", values[i])
			} else if value.Valid {
				_m.InviteCount = int(value.Int64)
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwnedProjects queries the "owned_projects" edge of the User entity.
func (_m *User) QueryOwnedProjects() *ProjectQuery {
	return NewUserClient(_m.config).QueryOwnedProjects(_m)
}

// QueryOwnedTeams queries the "owned_teams" edge of the User entity.
func (_m *User) QueryOwnedTeams() *TeamQuery {
	return NewUserClient(_m.config).QueryOwnedTeams(_m)
}

// QueryTeamMemberships queries the "team_memberships" edge of the User entity.
func (_m *User) QueryTeamMemberships() *TeamMemberQuery {
	return NewUserClient(_m.config).QueryTeamMemberships(_m)
}

// QueryProjectMemberships queries the "project_memberships" edge of the User entity.
func (_m *User) QueryProjectMemberships() *ProjectMemberQuery {
	return NewUserClient(_m.config).QueryProjectMemberships(_m)
}

// QueryProjectMembershipsGranted queries the "project_memberships_granted" edge of the User entity.
func (_m *User) QueryProjectMembershipsGranted() *ProjectMemberQuery {
	return NewUserClient(_m.config).QueryProjectMembershipsGranted(_m)
}

// QueryTasksAssigned queries the "tasks_assigned" edge of the User entity.
func (_m *User) QueryTasksAssigned() *TaskQuery {
	return NewUserClient(_m.config).QueryTasksAssigned(_m)
}

// QueryTaskAssignees queries the "task_assignees" edge of the User entity.
func (_m *User) QueryTaskAssignees() *TaskAssigneeQuery {
	return NewUserClient(_m.config).QueryTaskAssignees(_m)
}

// QuerySprints queries the "sprints" edge of the User entity.
func (_m *User) QuerySprints() *SprintQuery {
	return NewUserClient(_m.config).QuerySprints(_m)
}

// QueryTags queries the "tags" edge of the User entity.
func (_m *User) QueryTags() *TagQuery {
	return NewUserClient(_m.config).QueryTags(_m)
}

// QueryAPIKeys queries the "api_keys" edge of the User entity.
func (_m *User) QueryAPIKeys() *APIKeyQuery {
	return NewUserClient(_m.config).QueryAPIKeys(_m)
}

// QueryUserActivities queries the "user_activities" edge of the User entity.
func (_m *User) QueryUserActivities() *UserActivityQuery {
	return NewUserClient(_m.config).QueryUserActivities(_m)
}

// QueryTaskComments queries the "task_comments" edge of the User entity.
func (_m *User) QueryTaskComments() *TaskCommentQuery {
	return NewUserClient(_m.config).QueryTaskComments(_m)
}

// QueryInvitesSent queries the "invites_sent" edge of the User entity.
func (_m *User) QueryInvitesSent() *InviteQuery {
	return NewUserClient(_m.config).QueryInvitesSent(_m)
}

// QueryInvitesReceived queries the "invites_received" edge of the User entity.
func (_m *User) QueryInvitesReceived() *InviteQuery {
	return NewUserClient(_m.config).QueryInvitesReceived(_m)
}

// QueryTeamInvitationsSent queries the "team_invitations_sent" edge of the User entity.
func (_m *User) QueryTeamInvitationsSent() *TeamInvitationQuery {
	return NewUserClient(_m.config).QueryTeamInvitationsSent(_m)
}

// QueryTeamInvitationsReceived queries the "team_invitations_received" edge of the User entity.
func (_m *User) QueryTeamInvitationsReceived() *TeamInvitationQuery {
	return NewUserClient(_m.config).QueryTeamInvitationsReceived(_m)
}

// QueryCloudinaryCredentials queries the "cloudinary_credentials" edge of the User entity.
func (_m *User) QueryCloudinaryCredentials() *CloudinaryCredentialQuery {
	return NewUserClient(_m.config).QueryCloudinaryCredentials(_m)
}

// QueryTaskAttachments queries the "task_attachments" edge of the User entity.
func (_m *User) QueryTaskAttachments() *TaskAttachmentQuery {
	return NewUserClient(_m.config).QueryTaskAttachments(_m)
}

// QueryWikiPagesCreated queries the "wiki_pages_created" edge of the User entity.
func (_m *User) QueryWikiPagesCreated() *WikiPageQuery {
	return NewUserClient(_m.config).QueryWikiPagesCreated(_m)
}

// QueryYjsUpdates queries the "yjs_updates" edge of the User entity.
func (_m *User) QueryYjsUpdates() *YjsUpdateQuery {
	return NewUserClient(_m.config).QueryYjsUpdates(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FirstName; v != nil {
		builder.WriteString("first_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastName; v != nil {
		builder.WriteString("last_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_admin=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsAdmin))
	builder.WriteString(", ")
	builder.WriteString("totp_secret=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("totp_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotpEnabled))
	builder.WriteString(", ")
	builder.WriteString("backup_codes=<sensitive>")
	builder.WriteString(", ")
	if v := _m.PasswordChangedAt; v != nil {
		builder.WriteString("password_changed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("invite_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
