// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/apikey"
	"taskai/ent/cloudinarycredential"
	"taskai/ent/invite"
	"taskai/ent/project"
	"taskai/ent/projectmember"
	"taskai/ent/sprint"
	"taskai/ent/tag"
	"taskai/ent/task"
	"taskai/ent/taskassignee"
	"taskai/ent/taskattachment"
	"taskai/ent/taskcomment"
	"taskai/ent/team"
	"taskai/ent/teaminvitation"
	"taskai/ent/teammember"
	"taskai/ent/user"
	"taskai/ent/useractivity"
	"taskai/ent/wikipage"
	"taskai/ent/yjsupdate"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (_c *UserCreate) SetEmail(v string) *UserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *UserCreate) SetPasswordHash(v string) *UserCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetName sets the "name" field.
func (_c *UserCreate) SetName(v string) *UserCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *UserCreate) SetNillableName(v *string) *UserCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetFirstName sets the "first_name" field.
func (_c *UserCreate) SetFirstName(v string) *UserCreate {
	_c.mutation.SetFirstName(v)
	return _c
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_c *UserCreate) SetNillableFirstName(v *string) *UserCreate {
	if v != nil {
		_c.SetFirstName(*v)
	}
	return _c
}

// SetLastName sets the "last_name" field.
func (_c *UserCreate) SetLastName(v string) *UserCreate {
	_c.mutation.SetLastName(v)
	return _c
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_c *UserCreate) SetNillableLastName(v *string) *UserCreate {
	if v != nil {
		_c.SetLastName(*v)
	}
	return _c
}

// SetIsAdmin sets the "is_admin" field.
func (_c *UserCreate) SetIsAdmin(v bool) *UserCreate {
	_c.mutation.SetIsAdmin(v)
	return _c
}

// SetNillableIsAdmin sets the "is_admin" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsAdmin(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsAdmin(*v)
	}
	return _c
}

// SetTotpSecret sets the "totp_secret" field.
func (_c *UserCreate) SetTotpSecret(v string) *UserCreate {
	_c.mutation.SetTotpSecret(v)
	return _c
}

// SetNillableTotpSecret sets the "totp_secret" field if the given value is not nil.
func (_c *UserCreate) SetNillableTotpSecret(v *string) *UserCreate {
	if v != nil {
		_c.SetTotpSecret(*v)
	}
	return _c
}

// SetTotpEnabled sets the "totp_enabled" field.
func (_c *UserCreate) SetTotpEnabled(v bool) *UserCreate {
	_c.mutation.SetTotpEnabled(v)
	return _c
}

// SetNillableTotpEnabled sets the "totp_enabled" field if the given value is not nil.
func (_c *UserCreate) SetNillableTotpEnabled(v *bool) *UserCreate {
	if v != nil {
		_c.SetTotpEnabled(*v)
	}
	return _c
}

// SetBackupCodes sets the "backup_codes" field.
func (_c *UserCreate) SetBackupCodes(v string) *UserCreate {
	_c.mutation.SetBackupCodes(v)
	return _c
}

// SetNillableBackupCodes sets the "backup_codes" field if the given value is not nil.
func (_c *UserCreate) SetNillableBackupCodes(v *string) *UserCreate {
	if v != nil {
		_c.SetBackupCodes(*v)
	}
	return _c
}

// SetPasswordChangedAt sets the "password_changed_at" field.
func (_c *UserCreate) SetPasswordChangedAt(v time.Time) *UserCreate {
	_c.mutation.SetPasswordChangedAt(v)
	return _c
}

// SetNillablePasswordChangedAt sets the "password_changed_at" field if the given value is not nil.
func (_c *UserCreate) SetNillablePasswordChangedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetPasswordChangedAt(*v)
	}
	return _c
}

// SetInviteCount sets the "invite_count" field.
func (_c *UserCreate) SetInviteCount(v int) *UserCreate {
	_c.mutation.SetInviteCount(v)
	return _c
}

// SetNillableInviteCount sets the "invite_count" field if the given value is not nil.
func (_c *UserCreate) SetNillableInviteCount(v *int) *UserCreate {
	if v != nil {
		_c.SetInviteCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserCreate) SetUpdatedAt(v time.Time) *UserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableUpdatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserCreate) SetID(v int64) *UserCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddOwnedProjectIDs adds the "owned_projects" edge to the Project entity by IDs.
func (_c *UserCreate) AddOwnedProjectIDs(ids ...int64) *UserCreate {
	_c.mutation.AddOwnedProjectIDs(ids...)
	return _c
}

// AddOwnedProjects adds the "owned_projects" edges to the Project entity.
func (_c *UserCreate) AddOwnedProjects(v ...*Project) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOwnedProjectIDs(ids...)
}

// AddOwnedTeamIDs adds the "owned_teams" edge to the Team entity by IDs.
func (_c *UserCreate) AddOwnedTeamIDs(ids ...int64) *UserCreate {
	_c.mutation.AddOwnedTeamIDs(ids...)
	return _c
}

// AddOwnedTeams adds the "owned_teams" edges to the Team entity.
func (_c *UserCreate) AddOwnedTeams(v ...*Team) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOwnedTeamIDs(ids...)
}

// AddTeamMembershipIDs adds the "team_memberships" edge to the TeamMember entity by IDs.
func (_c *UserCreate) AddTeamMembershipIDs(ids ...int64) *UserCreate {
	_c.mutation.AddTeamMembershipIDs(ids...)
	return _c
}

// AddTeamMemberships adds the "team_memberships" edges to the TeamMember entity.
func (_c *UserCreate) AddTeamMemberships(v ...*TeamMember) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeamMembershipIDs(ids...)
}

// AddProjectMembershipIDs adds the "project_memberships" edge to the ProjectMember entity by IDs.
func (_c *UserCreate) AddProjectMembershipIDs(ids ...int64) *UserCreate {
	_c.mutation.AddProjectMembershipIDs(ids...)
	return _c
}

// AddProjectMemberships adds the "project_memberships" edges to the ProjectMember entity.
func (_c *UserCreate) AddProjectMemberships(v ...*ProjectMember) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProjectMembershipIDs(ids...)
}

// AddProjectMembershipsGrantedIDs adds the "project_memberships_granted" edge to the ProjectMember entity by IDs.
func (_c *UserCreate) AddProjectMembershipsGrantedIDs(ids ...int64) *UserCreate {
	_c.mutation.AddProjectMembershipsGrantedIDs(ids...)
	return _c
}

// AddProjectMembershipsGranted adds the "project_memberships_granted" edges to the ProjectMember entity.
func (_c *UserCreate) AddProjectMembershipsGranted(v ...*ProjectMember) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProjectMembershipsGrantedIDs(ids...)
}

// AddTasksAssignedIDs adds the "tasks_assigned" edge to the Task entity by IDs.
func (_c *UserCreate) AddTasksAssignedIDs(ids ...int64) *UserCreate {
	_c.mutation.AddTasksAssignedIDs(ids...)
	return _c
}

// AddTasksAssigned adds the "tasks_assigned" edges to the Task entity.
func (_c *UserCreate) AddTasksAssigned(v ...*Task) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTasksAssignedIDs(ids...)
}

// AddTaskAssigneeIDs adds the "task_assignees" edge to the TaskAssignee entity by IDs.
func (_c *UserCreate) AddTaskAssigneeIDs(ids ...int) *UserCreate {
	_c.mutation.AddTaskAssigneeIDs(ids...)
	return _c
}

// AddTaskAssignees adds the "task_assignees" edges to the TaskAssignee entity.
func (_c *UserCreate) AddTaskAssignees(v ...*TaskAssignee) *UserCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskAssigneeIDs(ids...)
}

// AddSprintIDs adds the "sprints" edge to the Sprint entity by IDs.
func (_c *UserCreate) AddSprintIDs(ids ...int64) *UserCreate {
	_c.mutation.AddSprintIDs(ids...)
	return _c
}

// AddSprints adds the "sprints" edges to the Sprint entity.
func (_c *UserCreate) AddSprints(v ...*Sprint) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSprintIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_c *UserCreate) AddTagIDs(ids ...int64) *UserCreate {
	_c.mutation.AddTagIDs(ids...)
	return _c
}

// AddTags adds the "tags" edges to the Tag entity.
func (_c *UserCreate) AddTags(v ...*Tag) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTagIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_c *UserCreate) AddAPIKeyIDs(ids ...int64) *UserCreate {
	_c.mutation.AddAPIKeyIDs(ids...)
	return _c
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_c *UserCreate) AddAPIKeys(v ...*APIKey) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAPIKeyIDs(ids...)
}

// AddUserActivityIDs adds the "user_activities" edge to the UserActivity entity by IDs.
func (_c *UserCreate) AddUserActivityIDs(ids ...int64) *UserCreate {
	_c.mutation.AddUserActivityIDs(ids...)
	return _c
}

// AddUserActivities adds the "user_activities" edges to the UserActivity entity.
func (_c *UserCreate) AddUserActivities(v ...*UserActivity) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserActivityIDs(ids...)
}

// AddTaskCommentIDs adds the "task_comments" edge to the TaskComment entity by IDs.
func (_c *UserCreate) AddTaskCommentIDs(ids ...int64) *UserCreate {
	_c.mutation.AddTaskCommentIDs(ids...)
	return _c
}

// AddTaskComments adds the "task_comments" edges to the TaskComment entity.
func (_c *UserCreate) AddTaskComments(v ...*TaskComment) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskCommentIDs(ids...)
}

// AddInvitesSentIDs adds the "invites_sent" edge to the Invite entity by IDs.
func (_c *UserCreate) AddInvitesSentIDs(ids ...int64) *UserCreate {
	_c.mutation.AddInvitesSentIDs(ids...)
	return _c
}

// AddInvitesSent adds the "invites_sent" edges to the Invite entity.
func (_c *UserCreate) AddInvitesSent(v ...*Invite) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInvitesSentIDs(ids...)
}

// AddInvitesReceivedIDs adds the "invites_received" edge to the Invite entity by IDs.
func (_c *UserCreate) AddInvitesReceivedIDs(ids ...int64) *UserCreate {
	_c.mutation.AddInvitesReceivedIDs(ids...)
	return _c
}

// AddInvitesReceived adds the "invites_received" edges to the Invite entity.
func (_c *UserCreate) AddInvitesReceived(v ...*Invite) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInvitesReceivedIDs(ids...)
}

// AddTeamInvitationsSentIDs adds the "team_invitations_sent" edge to the TeamInvitation entity by IDs.
func (_c *UserCreate) AddTeamInvitationsSentIDs(ids ...int64) *UserCreate {
	_c.mutation.AddTeamInvitationsSentIDs(ids...)
	return _c
}

// AddTeamInvitationsSent adds the "team_invitations_sent" edges to the TeamInvitation entity.
func (_c *UserCreate) AddTeamInvitationsSent(v ...*TeamInvitation) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeamInvitationsSentIDs(ids...)
}

// AddTeamInvitationsReceivedIDs adds the "team_invitations_received" edge to the TeamInvitation entity by IDs.
func (_c *UserCreate) AddTeamInvitationsReceivedIDs(ids ...int64) *UserCreate {
	_c.mutation.AddTeamInvitationsReceivedIDs(ids...)
	return _c
}

// AddTeamInvitationsReceived adds the "team_invitations_received" edges to the TeamInvitation entity.
func (_c *UserCreate) AddTeamInvitationsReceived(v ...*TeamInvitation) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeamInvitationsReceivedIDs(ids...)
}

// AddCloudinaryCredentialIDs adds the "cloudinary_credentials" edge to the CloudinaryCredential entity by IDs.
func (_c *UserCreate) AddCloudinaryCredentialIDs(ids ...int64) *UserCreate {
	_c.mutation.AddCloudinaryCredentialIDs(ids...)
	return _c
}

// AddCloudinaryCredentials adds the "cloudinary_credentials" edges to the CloudinaryCredential entity.
func (_c *UserCreate) AddCloudinaryCredentials(v ...*CloudinaryCredential) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCloudinaryCredentialIDs(ids...)
}

// AddTaskAttachmentIDs adds the "task_attachments" edge to the TaskAttachment entity by IDs.
func (_c *UserCreate) AddTaskAttachmentIDs(ids ...int64) *UserCreate {
	_c.mutation.AddTaskAttachmentIDs(ids...)
	return _c
}

// AddTaskAttachments adds the "task_attachments" edges to the TaskAttachment entity.
func (_c *UserCreate) AddTaskAttachments(v ...*TaskAttachment) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskAttachmentIDs(ids...)
}

// AddWikiPagesCreatedIDs adds the "wiki_pages_created" edge to the WikiPage entity by IDs.
func (_c *UserCreate) AddWikiPagesCreatedIDs(ids ...int64) *UserCreate {
	_c.mutation.AddWikiPagesCreatedIDs(ids...)
	return _c
}

// AddWikiPagesCreated adds the "wiki_pages_created" edges to the WikiPage entity.
func (_c *UserCreate) AddWikiPagesCreated(v ...*WikiPage) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWikiPagesCreatedIDs(ids...)
}

// AddYjsUpdateIDs adds the "yjs_updates" edge to the YjsUpdate entity by IDs.
func (_c *UserCreate) AddYjsUpdateIDs(ids ...int64) *UserCreate {
	_c.mutation.AddYjsUpdateIDs(ids...)
	return _c
}

// AddYjsUpdates adds the "yjs_updates" edges to the YjsUpdate entity.
func (_c *UserCreate) AddYjsUpdates(v ...*YjsUpdate) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddYjsUpdateIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.IsAdmin(); !ok {
		v := user.DefaultIsAdmin
		_c.mutation.SetIsAdmin(v)
	}
	if _, ok := _c.mutation.TotpEnabled(); !ok {
		v := user.DefaultTotpEnabled
		_c.mutation.SetTotpEnabled(v)
	}
	if _, ok := _c.mutation.InviteCount(); !ok {
		v := user.DefaultInviteCount
		_c.mutation.SetInviteCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := user.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "User.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "User.password_hash"`)}
	}
	if v, ok := _c.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsAdmin(); !ok {
		return &ValidationError{Name: "is_admin", err: errors.New(`ent: missing required field "User.is_admin"`)}
	}
	if _, ok := _c.mutation.TotpEnabled(); !ok {
		return &ValidationError{Name: "totp_enabled", err: errors.New(`ent: missing required field "User.totp_enabled"`)}
	}
	if _, ok := _c.mutation.InviteCount(); !ok {
		return &ValidationError{Name: "invite_count", err: errors.New(`ent: missing required field "User.invite_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "User.updated_at"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.FirstName(); ok {
		_spec.SetField(user.FieldFirstName, field.TypeString, value)
		_node.FirstName = &value
	}
	if value, ok := _c.mutation.LastName(); ok {
		_spec.SetField(user.FieldLastName, field.TypeString, value)
		_node.LastName = &value
	}
	if value, ok := _c.mutation.IsAdmin(); ok {
		_spec.SetField(user.FieldIsAdmin, field.TypeBool, value)
		_node.IsAdmin = value
	}
	if value, ok := _c.mutation.TotpSecret(); ok {
		_spec.SetField(user.FieldTotpSecret, field.TypeString, value)
		_node.TotpSecret = &value
	}
	if value, ok := _c.mutation.TotpEnabled(); ok {
		_spec.SetField(user.FieldTotpEnabled, field.TypeBool, value)
		_node.TotpEnabled = value
	}
	if value, ok := _c.mutation.BackupCodes(); ok {
		_spec.SetField(user.FieldBackupCodes, field.TypeString, value)
		_node.BackupCodes = &value
	}
	if value, ok := _c.mutation.PasswordChangedAt(); ok {
		_spec.SetField(user.FieldPasswordChangedAt, field.TypeTime, value)
		_node.PasswordChangedAt = &value
	}
	if value, ok := _c.mutation.InviteCount(); ok {
		_spec.SetField(user.FieldInviteCount, field.TypeInt, value)
		_node.InviteCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OwnedProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedProjectsTable,
			Columns: []string{user.OwnedProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OwnedTeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OwnedTeamsTable,
			Columns: []string{user.OwnedTeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeamMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TeamMembershipsTable,
			Columns: []string{user.TeamMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teammember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProjectMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProjectMembershipsTable,
			Columns: []string{user.ProjectMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProjectMembershipsGrantedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ProjectMembershipsGrantedTable,
			Columns: []string{user.ProjectMembershipsGrantedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TasksAssignedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TasksAssignedTable,
			Columns: []string{user.TasksAssignedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TaskAssigneesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TaskAssigneesTable,
			Columns: []string{user.TaskAssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SprintsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SprintsTable,
			Columns: []string{user.SprintsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sprint.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TagsTable,
			Columns: []string{user.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.APIKeysTable,
			Columns: []string{user.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UserActivitiesTable,
			Columns: []string{user.UserActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useractivity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TaskCommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TaskCommentsTable,
			Columns: []string{user.TaskCommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskcomment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InvitesSentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InvitesSentTable,
			Columns: []string{user.InvitesSentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InvitesReceivedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InvitesReceivedTable,
			Columns: []string{user.InvitesReceivedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeamInvitationsSentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TeamInvitationsSentTable,
			Columns: []string{user.TeamInvitationsSentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teaminvitation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeamInvitationsReceivedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TeamInvitationsReceivedTable,
			Columns: []string{user.TeamInvitationsReceivedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teaminvitation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CloudinaryCredentialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CloudinaryCredentialsTable,
			Columns: []string{user.CloudinaryCredentialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cloudinarycredential.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TaskAttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.TaskAttachmentsTable,
			Columns: []string{user.TaskAttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskattachment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WikiPagesCreatedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.WikiPagesCreatedTable,
			Columns: []string{user.WikiPagesCreatedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.YjsUpdatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.YjsUpdatesTable,
			Columns: []string{user.YjsUpdatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yjsupdate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
