// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"taskai/ent/project"
	"taskai/ent/user"
	"taskai/ent/wikipage"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// WikiPage is the model entity for the WikiPage schema.
type WikiPage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID int64 `json:"project_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WikiPageQuery when eager-loading is set.
	Edges        WikiPageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WikiPageEdges holds the relations/edges for other nodes in the graph.
type WikiPageEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// YjsUpdates holds the value of the yjs_updates edge.
	YjsUpdates []*YjsUpdate `json:"yjs_updates,omitempty"`
	// Versions holds the value of the versions edge.
	Versions []*PageVersion `json:"versions,omitempty"`
	// Blocks holds the value of the blocks edge.
	Blocks []*WikiBlock `json:"blocks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WikiPageEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WikiPageEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// YjsUpdatesOrErr returns the YjsUpdates value or an error if the edge
// was not loaded in eager-loading.
func (e WikiPageEdges) YjsUpdatesOrErr() ([]*YjsUpdate, error) {
	if e.loadedTypes[2] {
		return e.YjsUpdates, nil
	}
	return nil, &NotLoadedError{edge: "yjs_updates"}
}

// VersionsOrErr returns the Versions value or an error if the edge
// was not loaded in eager-loading.
func (e WikiPageEdges) VersionsOrErr() ([]*PageVersion, error) {
	if e.loadedTypes[3] {
		return e.Versions, nil
	}
	return nil, &NotLoadedError{edge: "versions"}
}

// BlocksOrErr returns the Blocks value or an error if the edge
// was not loaded in eager-loading.
func (e WikiPageEdges) BlocksOrErr() ([]*WikiBlock, error) {
	if e.loadedTypes[4] {
		return e.Blocks, nil
	}
	return nil, &NotLoadedError{edge: "blocks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WikiPage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wikipage.FieldID, wikipage.FieldProjectID, wikipage.FieldCreatedBy:
			values[i] = new(sql.NullInt64)
		case wikipage.FieldTitle, wikipage.FieldSlug, wikipage.FieldContent:
			values[i] = new(sql.NullString)
		case wikipage.FieldCreatedAt, wikipage.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WikiPage fields.
func (_m *WikiPage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wikipage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case wikipage.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = value.Int64
			}
		case wikipage.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case wikipage.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case wikipage.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case wikipage.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case wikipage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case wikipage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WikiPage.
// This includes values selected through modifiers, order, etc.
func (_m *WikiPage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the WikiPage entity.
func (_m *WikiPage) QueryProject() *ProjectQuery {
	return NewWikiPageClient(_m.config).QueryProject(_m)
}

// QueryCreator queries the "creator" edge of the WikiPage entity.
func (_m *WikiPage) QueryCreator() *UserQuery {
	return NewWikiPageClient(_m.config).QueryCreator(_m)
}

// QueryYjsUpdates queries the "yjs_updates" edge of the WikiPage entity.
func (_m *WikiPage) QueryYjsUpdates() *YjsUpdateQuery {
	return NewWikiPageClient(_m.config).QueryYjsUpdates(_m)
}

// QueryVersions queries the "versions" edge of the WikiPage entity.
func (_m *WikiPage) QueryVersions() *PageVersionQuery {
	return NewWikiPageClient(_m.config).QueryVersions(_m)
}

// QueryBlocks queries the "blocks" edge of the WikiPage entity.
func (_m *WikiPage) QueryBlocks() *WikiBlockQuery {
	return NewWikiPageClient(_m.config).QueryBlocks(_m)
}

// Update returns a builder for updating this WikiPage.
// Note that you need to call WikiPage.Unwrap() before calling this method if this WikiPage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WikiPage) Update() *WikiPageUpdateOne {
	return NewWikiPageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WikiPage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WikiPage) Unwrap() *WikiPage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WikiPage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WikiPage) String() string {
	var builder strings.Builder
	builder.WriteString("WikiPage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WikiPages is a parsable slice of WikiPage.
type WikiPages []*WikiPage
