// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/pageversion"
	"taskai/ent/predicate"
	"taskai/ent/project"
	"taskai/ent/user"
	"taskai/ent/wikiblock"
	"taskai/ent/wikipage"
	"taskai/ent/yjsupdate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WikiPageUpdate is the builder for updating WikiPage entities.
type WikiPageUpdate struct {
	config
	hooks    []Hook
	mutation *WikiPageMutation
}

// Where appends a list predicates to the WikiPageUpdate builder.
func (_u *WikiPageUpdate) Where(ps ...predicate.WikiPage) *WikiPageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *WikiPageUpdate) SetProjectID(v int64) *WikiPageUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *WikiPageUpdate) SetNillableProjectID(v *int64) *WikiPageUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *WikiPageUpdate) SetTitle(v string) *WikiPageUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *WikiPageUpdate) SetNillableTitle(v *string) *WikiPageUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *WikiPageUpdate) SetSlug(v string) *WikiPageUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *WikiPageUpdate) SetNillableSlug(v *string) *WikiPageUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *WikiPageUpdate) SetContent(v string) *WikiPageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *WikiPageUpdate) SetNillableContent(v *string) *WikiPageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *WikiPageUpdate) SetCreatedBy(v int64) *WikiPageUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *WikiPageUpdate) SetNillableCreatedBy(v *int64) *WikiPageUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WikiPageUpdate) SetUpdatedAt(v time.Time) *WikiPageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *WikiPageUpdate) SetProject(v *Project) *WikiPageUpdate {
	return _u.SetProjectID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *WikiPageUpdate) SetCreatorID(id int64) *WikiPageUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *WikiPageUpdate) SetCreator(v *User) *WikiPageUpdate {
	return _u.SetCreatorID(v.ID)
}

// AddYjsUpdateIDs adds the "yjs_updates" edge to the YjsUpdate entity by IDs.
func (_u *WikiPageUpdate) AddYjsUpdateIDs(ids ...int64) *WikiPageUpdate {
	_u.mutation.AddYjsUpdateIDs(ids...)
	return _u
}

// AddYjsUpdates adds the "yjs_updates" edges to the YjsUpdate entity.
func (_u *WikiPageUpdate) AddYjsUpdates(v ...*YjsUpdate) *WikiPageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddYjsUpdateIDs(ids...)
}

// AddVersionIDs adds the "versions" edge to the PageVersion entity by IDs.
func (_u *WikiPageUpdate) AddVersionIDs(ids ...int64) *WikiPageUpdate {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the PageVersion entity.
func (_u *WikiPageUpdate) AddVersions(v ...*PageVersion) *WikiPageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// AddBlockIDs adds the "blocks" edge to the WikiBlock entity by IDs.
func (_u *WikiPageUpdate) AddBlockIDs(ids ...int64) *WikiPageUpdate {
	_u.mutation.AddBlockIDs(ids...)
	return _u
}

// AddBlocks adds the "blocks" edges to the WikiBlock entity.
func (_u *WikiPageUpdate) AddBlocks(v ...*WikiBlock) *WikiPageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBlockIDs(ids...)
}

// Mutation returns the WikiPageMutation object of the builder.
func (_u *WikiPageUpdate) Mutation() *WikiPageMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *WikiPageUpdate) ClearProject() *WikiPageUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *WikiPageUpdate) ClearCreator() *WikiPageUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearYjsUpdates clears all "yjs_updates" edges to the YjsUpdate entity.
func (_u *WikiPageUpdate) ClearYjsUpdates() *WikiPageUpdate {
	_u.mutation.ClearYjsUpdates()
	return _u
}

// RemoveYjsUpdateIDs removes the "yjs_updates" edge to YjsUpdate entities by IDs.
func (_u *WikiPageUpdate) RemoveYjsUpdateIDs(ids ...int64) *WikiPageUpdate {
	_u.mutation.RemoveYjsUpdateIDs(ids...)
	return _u
}

// RemoveYjsUpdates removes "yjs_updates" edges to YjsUpdate entities.
func (_u *WikiPageUpdate) RemoveYjsUpdates(v ...*YjsUpdate) *WikiPageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveYjsUpdateIDs(ids...)
}

// ClearVersions clears all "versions" edges to the PageVersion entity.
func (_u *WikiPageUpdate) ClearVersions() *WikiPageUpdate {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to PageVersion entities by IDs.
func (_u *WikiPageUpdate) RemoveVersionIDs(ids ...int64) *WikiPageUpdate {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to PageVersion entities.
func (_u *WikiPageUpdate) RemoveVersions(v ...*PageVersion) *WikiPageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// ClearBlocks clears all "blocks" edges to the WikiBlock entity.
func (_u *WikiPageUpdate) ClearBlocks() *WikiPageUpdate {
	_u.mutation.ClearBlocks()
	return _u
}

// RemoveBlockIDs removes the "blocks" edge to WikiBlock entities by IDs.
func (_u *WikiPageUpdate) RemoveBlockIDs(ids ...int64) *WikiPageUpdate {
	_u.mutation.RemoveBlockIDs(ids...)
	return _u
}

// RemoveBlocks removes "blocks" edges to WikiBlock entities.
func (_u *WikiPageUpdate) RemoveBlocks(v ...*WikiBlock) *WikiPageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBlockIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WikiPageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WikiPageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WikiPageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WikiPageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WikiPageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wikipage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WikiPageUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := wikipage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "WikiPage.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := wikipage.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "WikiPage.slug": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WikiPage.project"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WikiPage.creator"`)
	}
	return nil
}

func (_u *WikiPageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wikipage.Table, wikipage.Columns, sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(wikipage.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(wikipage.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(wikipage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wikipage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.ProjectTable,
			Columns: []string{wikipage.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.ProjectTable,
			Columns: []string{wikipage.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.CreatorTable,
			Columns: []string{wikipage.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.CreatorTable,
			Columns: []string{wikipage.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.YjsUpdatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.YjsUpdatesTable,
			Columns: []string{wikipage.YjsUpdatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yjsupdate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedYjsUpdatesIDs(); len(nodes) > 0 && !_u.mutation.YjsUpdatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.YjsUpdatesTable,
			Columns: []string{wikipage.YjsUpdatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yjsupdate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.YjsUpdatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.YjsUpdatesTable,
			Columns: []string{wikipage.YjsUpdatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yjsupdate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.VersionsTable,
			Columns: []string{wikipage.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pageversion.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.VersionsTable,
			Columns: []string{wikipage.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pageversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.VersionsTable,
			Columns: []string{wikipage.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pageversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.BlocksTable,
			Columns: []string{wikipage.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikiblock.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlocksIDs(); len(nodes) > 0 && !_u.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.BlocksTable,
			Columns: []string{wikipage.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikiblock.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.BlocksTable,
			Columns: []string{wikipage.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikiblock.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wikipage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WikiPageUpdateOne is the builder for updating a single WikiPage entity.
type WikiPageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WikiPageMutation
}

// SetProjectID sets the "project_id" field.
func (_u *WikiPageUpdateOne) SetProjectID(v int64) *WikiPageUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *WikiPageUpdateOne) SetNillableProjectID(v *int64) *WikiPageUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *WikiPageUpdateOne) SetTitle(v string) *WikiPageUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *WikiPageUpdateOne) SetNillableTitle(v *string) *WikiPageUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *WikiPageUpdateOne) SetSlug(v string) *WikiPageUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *WikiPageUpdateOne) SetNillableSlug(v *string) *WikiPageUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *WikiPageUpdateOne) SetContent(v string) *WikiPageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *WikiPageUpdateOne) SetNillableContent(v *string) *WikiPageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *WikiPageUpdateOne) SetCreatedBy(v int64) *WikiPageUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *WikiPageUpdateOne) SetNillableCreatedBy(v *int64) *WikiPageUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WikiPageUpdateOne) SetUpdatedAt(v time.Time) *WikiPageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *WikiPageUpdateOne) SetProject(v *Project) *WikiPageUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *WikiPageUpdateOne) SetCreatorID(id int64) *WikiPageUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *WikiPageUpdateOne) SetCreator(v *User) *WikiPageUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// AddYjsUpdateIDs adds the "yjs_updates" edge to the YjsUpdate entity by IDs.
func (_u *WikiPageUpdateOne) AddYjsUpdateIDs(ids ...int64) *WikiPageUpdateOne {
	_u.mutation.AddYjsUpdateIDs(ids...)
	return _u
}

// AddYjsUpdates adds the "yjs_updates" edges to the YjsUpdate entity.
func (_u *WikiPageUpdateOne) AddYjsUpdates(v ...*YjsUpdate) *WikiPageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddYjsUpdateIDs(ids...)
}

// AddVersionIDs adds the "versions" edge to the PageVersion entity by IDs.
func (_u *WikiPageUpdateOne) AddVersionIDs(ids ...int64) *WikiPageUpdateOne {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the PageVersion entity.
func (_u *WikiPageUpdateOne) AddVersions(v ...*PageVersion) *WikiPageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// AddBlockIDs adds the "blocks" edge to the WikiBlock entity by IDs.
func (_u *WikiPageUpdateOne) AddBlockIDs(ids ...int64) *WikiPageUpdateOne {
	_u.mutation.AddBlockIDs(ids...)
	return _u
}

// AddBlocks adds the "blocks" edges to the WikiBlock entity.
func (_u *WikiPageUpdateOne) AddBlocks(v ...*WikiBlock) *WikiPageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBlockIDs(ids...)
}

// Mutation returns the WikiPageMutation object of the builder.
func (_u *WikiPageUpdateOne) Mutation() *WikiPageMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *WikiPageUpdateOne) ClearProject() *WikiPageUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *WikiPageUpdateOne) ClearCreator() *WikiPageUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearYjsUpdates clears all "yjs_updates" edges to the YjsUpdate entity.
func (_u *WikiPageUpdateOne) ClearYjsUpdates() *WikiPageUpdateOne {
	_u.mutation.ClearYjsUpdates()
	return _u
}

// RemoveYjsUpdateIDs removes the "yjs_updates" edge to YjsUpdate entities by IDs.
func (_u *WikiPageUpdateOne) RemoveYjsUpdateIDs(ids ...int64) *WikiPageUpdateOne {
	_u.mutation.RemoveYjsUpdateIDs(ids...)
	return _u
}

// RemoveYjsUpdates removes "yjs_updates" edges to YjsUpdate entities.
func (_u *WikiPageUpdateOne) RemoveYjsUpdates(v ...*YjsUpdate) *WikiPageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveYjsUpdateIDs(ids...)
}

// ClearVersions clears all "versions" edges to the PageVersion entity.
func (_u *WikiPageUpdateOne) ClearVersions() *WikiPageUpdateOne {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to PageVersion entities by IDs.
func (_u *WikiPageUpdateOne) RemoveVersionIDs(ids ...int64) *WikiPageUpdateOne {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to PageVersion entities.
func (_u *WikiPageUpdateOne) RemoveVersions(v ...*PageVersion) *WikiPageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// ClearBlocks clears all "blocks" edges to the WikiBlock entity.
func (_u *WikiPageUpdateOne) ClearBlocks() *WikiPageUpdateOne {
	_u.mutation.ClearBlocks()
	return _u
}

// RemoveBlockIDs removes the "blocks" edge to WikiBlock entities by IDs.
func (_u *WikiPageUpdateOne) RemoveBlockIDs(ids ...int64) *WikiPageUpdateOne {
	_u.mutation.RemoveBlockIDs(ids...)
	return _u
}

// RemoveBlocks removes "blocks" edges to WikiBlock entities.
func (_u *WikiPageUpdateOne) RemoveBlocks(v ...*WikiBlock) *WikiPageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBlockIDs(ids...)
}

// Where appends a list predicates to the WikiPageUpdate builder.
func (_u *WikiPageUpdateOne) Where(ps ...predicate.WikiPage) *WikiPageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WikiPageUpdateOne) Select(field string, fields ...string) *WikiPageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WikiPage entity.
func (_u *WikiPageUpdateOne) Save(ctx context.Context) (*WikiPage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WikiPageUpdateOne) SaveX(ctx context.Context) *WikiPage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WikiPageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WikiPageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WikiPageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wikipage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WikiPageUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := wikipage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "WikiPage.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := wikipage.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "WikiPage.slug": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WikiPage.project"`)
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WikiPage.creator"`)
	}
	return nil
}

func (_u *WikiPageUpdateOne) sqlSave(ctx context.Context) (_node *WikiPage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wikipage.Table, wikipage.Columns, sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WikiPage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wikipage.FieldID)
		for _, f := range fields {
			if !wikipage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wikipage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(wikipage.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(wikipage.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(wikipage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wikipage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.ProjectTable,
			Columns: []string{wikipage.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.ProjectTable,
			Columns: []string{wikipage.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.CreatorTable,
			Columns: []string{wikipage.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.CreatorTable,
			Columns: []string{wikipage.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.YjsUpdatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.YjsUpdatesTable,
			Columns: []string{wikipage.YjsUpdatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yjsupdate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedYjsUpdatesIDs(); len(nodes) > 0 && !_u.mutation.YjsUpdatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.YjsUpdatesTable,
			Columns: []string{wikipage.YjsUpdatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yjsupdate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.YjsUpdatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.YjsUpdatesTable,
			Columns: []string{wikipage.YjsUpdatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yjsupdate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.VersionsTable,
			Columns: []string{wikipage.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pageversion.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.VersionsTable,
			Columns: []string{wikipage.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pageversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.VersionsTable,
			Columns: []string{wikipage.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pageversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.BlocksTable,
			Columns: []string{wikipage.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikiblock.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBlocksIDs(); len(nodes) > 0 && !_u.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.BlocksTable,
			Columns: []string{wikipage.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikiblock.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.BlocksTable,
			Columns: []string{wikipage.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikiblock.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WikiPage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wikipage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
