// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"taskai/ent/pageversion"
	"taskai/ent/project"
	"taskai/ent/user"
	"taskai/ent/wikiblock"
	"taskai/ent/wikipage"
	"taskai/ent/yjsupdate"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WikiPageCreate is the builder for creating a WikiPage entity.
type WikiPageCreate struct {
	config
	mutation *WikiPageMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *WikiPageCreate) SetProjectID(v int64) *WikiPageCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *WikiPageCreate) SetTitle(v string) *WikiPageCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *WikiPageCreate) SetSlug(v string) *WikiPageCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *WikiPageCreate) SetContent(v string) *WikiPageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *WikiPageCreate) SetNillableContent(v *string) *WikiPageCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *WikiPageCreate) SetCreatedBy(v int64) *WikiPageCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WikiPageCreate) SetCreatedAt(v time.Time) *WikiPageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WikiPageCreate) SetNillableCreatedAt(v *time.Time) *WikiPageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WikiPageCreate) SetUpdatedAt(v time.Time) *WikiPageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WikiPageCreate) SetNillableUpdatedAt(v *time.Time) *WikiPageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WikiPageCreate) SetID(v int64) *WikiPageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *WikiPageCreate) SetProject(v *Project) *WikiPageCreate {
	return _c.SetProjectID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *WikiPageCreate) SetCreatorID(id int64) *WikiPageCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *WikiPageCreate) SetCreator(v *User) *WikiPageCreate {
	return _c.SetCreatorID(v.ID)
}

// AddYjsUpdateIDs adds the "yjs_updates" edge to the YjsUpdate entity by IDs.
func (_c *WikiPageCreate) AddYjsUpdateIDs(ids ...int64) *WikiPageCreate {
	_c.mutation.AddYjsUpdateIDs(ids...)
	return _c
}

// AddYjsUpdates adds the "yjs_updates" edges to the YjsUpdate entity.
func (_c *WikiPageCreate) AddYjsUpdates(v ...*YjsUpdate) *WikiPageCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddYjsUpdateIDs(ids...)
}

// AddVersionIDs adds the "versions" edge to the PageVersion entity by IDs.
func (_c *WikiPageCreate) AddVersionIDs(ids ...int64) *WikiPageCreate {
	_c.mutation.AddVersionIDs(ids...)
	return _c
}

// AddVersions adds the "versions" edges to the PageVersion entity.
func (_c *WikiPageCreate) AddVersions(v ...*PageVersion) *WikiPageCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVersionIDs(ids...)
}

// AddBlockIDs adds the "blocks" edge to the WikiBlock entity by IDs.
func (_c *WikiPageCreate) AddBlockIDs(ids ...int64) *WikiPageCreate {
	_c.mutation.AddBlockIDs(ids...)
	return _c
}

// AddBlocks adds the "blocks" edges to the WikiBlock entity.
func (_c *WikiPageCreate) AddBlocks(v ...*WikiBlock) *WikiPageCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBlockIDs(ids...)
}

// Mutation returns the WikiPageMutation object of the builder.
func (_c *WikiPageCreate) Mutation() *WikiPageMutation {
	return _c.mutation
}

// Save creates the WikiPage in the database.
func (_c *WikiPageCreate) Save(ctx context.Context) (*WikiPage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WikiPageCreate) SaveX(ctx context.Context) *WikiPage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WikiPageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WikiPageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WikiPageCreate) defaults() {
	if _, ok := _c.mutation.Content(); !ok {
		v := wikipage.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := wikipage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := wikipage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WikiPageCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "WikiPage.project_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "WikiPage.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := wikipage.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "WikiPage.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "WikiPage.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := wikipage.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "WikiPage.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "WikiPage.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WikiPage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WikiPage.updated_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "WikiPage.project"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "WikiPage.creator"`)}
	}
	return nil
}

func (_c *WikiPageCreate) sqlSave(ctx context.Context) (*WikiPage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WikiPageCreate) createSpec() (*WikiPage, *sqlgraph.CreateSpec) {
	var (
		_node = &WikiPage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wikipage.Table, sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(wikipage.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(wikipage.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(wikipage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(wikipage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(wikipage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.ProjectTable,
			Columns: []string{wikipage.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wikipage.CreatorTable,
			Columns: []string{wikipage.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.YjsUpdatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.YjsUpdatesTable,
			Columns: []string{wikipage.YjsUpdatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(yjsupdate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.VersionsTable,
			Columns: []string{wikipage.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pageversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wikipage.BlocksTable,
			Columns: []string{wikipage.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wikiblock.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WikiPageCreateBulk is the builder for creating many WikiPage entities in bulk.
type WikiPageCreateBulk struct {
	config
	err      error
	builders []*WikiPageCreate
}

// Save creates the WikiPage entities in the database.
func (_c *WikiPageCreateBulk) Save(ctx context.Context) ([]*WikiPage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WikiPage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WikiPageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WikiPageCreateBulk) SaveX(ctx context.Context) []*WikiPage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WikiPageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WikiPageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
