// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"taskai/ent/pageversion"
	"taskai/ent/predicate"
	"taskai/ent/project"
	"taskai/ent/user"
	"taskai/ent/wikiblock"
	"taskai/ent/wikipage"
	"taskai/ent/wikipageversion"
	"taskai/ent/yjsupdate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WikiPageQuery is the builder for querying WikiPage entities.
type WikiPageQuery struct {
	config
	ctx                  *QueryContext
	order                []wikipage.OrderOption
	inters               []Interceptor
	predicates           []predicate.WikiPage
	withProject          *ProjectQuery
	withCreator          *UserQuery
	withUpdater          *UserQuery
	withParent           *WikiPageQuery
	withChildren         *WikiPageQuery
	withYjsUpdates       *YjsUpdateQuery
	withVersions         *PageVersionQuery
	withWikiPageVersions *WikiPageVersionQuery
	withBlocks           *WikiBlockQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WikiPageQuery builder.
func (_q *WikiPageQuery) Where(ps ...predicate.WikiPage) *WikiPageQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *WikiPageQuery) Limit(limit int) *WikiPageQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *WikiPageQuery) Offset(offset int) *WikiPageQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *WikiPageQuery) Unique(unique bool) *WikiPageQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *WikiPageQuery) Order(o ...wikipage.OrderOption) *WikiPageQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProject chains the current query on the "project" edge.
func (_q *WikiPageQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wikipage.Table, wikipage.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, wikipage.ProjectTable, wikipage.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCreator chains the current query on the "creator" edge.
func (_q *WikiPageQuery) QueryCreator() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wikipage.Table, wikipage.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, wikipage.CreatorTable, wikipage.CreatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUpdater chains the current query on the "updater" edge.
func (_q *WikiPageQuery) QueryUpdater() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wikipage.Table, wikipage.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, wikipage.UpdaterTable, wikipage.UpdaterColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParent chains the current query on the "parent" edge.
func (_q *WikiPageQuery) QueryParent() *WikiPageQuery {
	query := (&WikiPageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wikipage.Table, wikipage.FieldID, selector),
			sqlgraph.To(wikipage.Table, wikipage.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, wikipage.ParentTable, wikipage.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChildren chains the current query on the "children" edge.
func (_q *WikiPageQuery) QueryChildren() *WikiPageQuery {
	query := (&WikiPageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wikipage.Table, wikipage.FieldID, selector),
			sqlgraph.To(wikipage.Table, wikipage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, wikipage.ChildrenTable, wikipage.ChildrenColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryYjsUpdates chains the current query on the "yjs_updates" edge.
func (_q *WikiPageQuery) QueryYjsUpdates() *YjsUpdateQuery {
	query := (&YjsUpdateClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wikipage.Table, wikipage.FieldID, selector),
			sqlgraph.To(yjsupdate.Table, yjsupdate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, wikipage.YjsUpdatesTable, wikipage.YjsUpdatesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVersions chains the current query on the "versions" edge.
func (_q *WikiPageQuery) QueryVersions() *PageVersionQuery {
	query := (&PageVersionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wikipage.Table, wikipage.FieldID, selector),
			sqlgraph.To(pageversion.Table, pageversion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, wikipage.VersionsTable, wikipage.VersionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWikiPageVersions chains the current query on the "wiki_page_versions" edge.
func (_q *WikiPageQuery) QueryWikiPageVersions() *WikiPageVersionQuery {
	query := (&WikiPageVersionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wikipage.Table, wikipage.FieldID, selector),
			sqlgraph.To(wikipageversion.Table, wikipageversion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, wikipage.WikiPageVersionsTable, wikipage.WikiPageVersionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBlocks chains the current query on the "blocks" edge.
func (_q *WikiPageQuery) QueryBlocks() *WikiBlockQuery {
	query := (&WikiBlockClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(wikipage.Table, wikipage.FieldID, selector),
			sqlgraph.To(wikiblock.Table, wikiblock.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, wikipage.BlocksTable, wikipage.BlocksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WikiPage entity from the query.
// Returns a *NotFoundError when no WikiPage was found.
func (_q *WikiPageQuery) First(ctx context.Context) (*WikiPage, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{wikipage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *WikiPageQuery) FirstX(ctx context.Context) *WikiPage {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WikiPage ID from the query.
// Returns a *NotFoundError when no WikiPage ID was found.
func (_q *WikiPageQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{wikipage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *WikiPageQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WikiPage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WikiPage entity is found.
// Returns a *NotFoundError when no WikiPage entities are found.
func (_q *WikiPageQuery) Only(ctx context.Context) (*WikiPage, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{wikipage.Label}
	default:
		return nil, &NotSingularError{wikipage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *WikiPageQuery) OnlyX(ctx context.Context) *WikiPage {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WikiPage ID in the query.
// Returns a *NotSingularError when more than one WikiPage ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *WikiPageQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{wikipage.Label}
	default:
		err = &NotSingularError{wikipage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *WikiPageQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WikiPages.
func (_q *WikiPageQuery) All(ctx context.Context) ([]*WikiPage, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WikiPage, *WikiPageQuery]()
	return withInterceptors[[]*WikiPage](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *WikiPageQuery) AllX(ctx context.Context) []*WikiPage {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WikiPage IDs.
func (_q *WikiPageQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(wikipage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *WikiPageQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *WikiPageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*WikiPageQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *WikiPageQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *WikiPageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *WikiPageQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WikiPageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *WikiPageQuery) Clone() *WikiPageQuery {
	if _q == nil {
		return nil
	}
	return &WikiPageQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]wikipage.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.WikiPage{}, _q.predicates...),
		withProject:          _q.withProject.Clone(),
		withCreator:          _q.withCreator.Clone(),
		withUpdater:          _q.withUpdater.Clone(),
		withParent:           _q.withParent.Clone(),
		withChildren:         _q.withChildren.Clone(),
		withYjsUpdates:       _q.withYjsUpdates.Clone(),
		withVersions:         _q.withVersions.Clone(),
		withWikiPageVersions: _q.withWikiPageVersions.Clone(),
		withBlocks:           _q.withBlocks.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WikiPageQuery) WithProject(opts ...func(*ProjectQuery)) *WikiPageQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// WithCreator tells the query-builder to eager-load the nodes that are connected to
// the "creator" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WikiPageQuery) WithCreator(opts ...func(*UserQuery)) *WikiPageQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCreator = query
	return _q
}

// WithUpdater tells the query-builder to eager-load the nodes that are connected to
// the "updater" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WikiPageQuery) WithUpdater(opts ...func(*UserQuery)) *WikiPageQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUpdater = query
	return _q
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WikiPageQuery) WithParent(opts ...func(*WikiPageQuery)) *WikiPageQuery {
	query := (&WikiPageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParent = query
	return _q
}

// WithChildren tells the query-builder to eager-load the nodes that are connected to
// the "children" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WikiPageQuery) WithChildren(opts ...func(*WikiPageQuery)) *WikiPageQuery {
	query := (&WikiPageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChildren = query
	return _q
}

// WithYjsUpdates tells the query-builder to eager-load the nodes that are connected to
// the "yjs_updates" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WikiPageQuery) WithYjsUpdates(opts ...func(*YjsUpdateQuery)) *WikiPageQuery {
	query := (&YjsUpdateClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withYjsUpdates = query
	return _q
}

// WithVersions tells the query-builder to eager-load the nodes that are connected to
// the "versions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WikiPageQuery) WithVersions(opts ...func(*PageVersionQuery)) *WikiPageQuery {
	query := (&PageVersionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVersions = query
	return _q
}

// WithWikiPageVersions tells the query-builder to eager-load the nodes that are connected to
// the "wiki_page_versions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WikiPageQuery) WithWikiPageVersions(opts ...func(*WikiPageVersionQuery)) *WikiPageQuery {
	query := (&WikiPageVersionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWikiPageVersions = query
	return _q
}

// WithBlocks tells the query-builder to eager-load the nodes that are connected to
// the "blocks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WikiPageQuery) WithBlocks(opts ...func(*WikiBlockQuery)) *WikiPageQuery {
	query := (&WikiBlockClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBlocks = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProjectID int64 `json:"project_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WikiPage.Query().
//		GroupBy(wikipage.FieldProjectID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *WikiPageQuery) GroupBy(field string, fields ...string) *WikiPageGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WikiPageGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = wikipage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProjectID int64 `json:"project_id,omitempty"`
//	}
//
//	client.WikiPage.Query().
//		Select(wikipage.FieldProjectID).
//		Scan(ctx, &v)
func (_q *WikiPageQuery) Select(fields ...string) *WikiPageSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &WikiPageSelect{WikiPageQuery: _q}
	sbuild.label = wikipage.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WikiPageSelect configured with the given aggregations.
func (_q *WikiPageQuery) Aggregate(fns ...AggregateFunc) *WikiPageSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *WikiPageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !wikipage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *WikiPageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WikiPage, error) {
	var (
		nodes       = []*WikiPage{}
		_spec       = _q.querySpec()
		loadedTypes = [9]bool{
			_q.withProject != nil,
			_q.withCreator != nil,
			_q.withUpdater != nil,
			_q.withParent != nil,
			_q.withChildren != nil,
			_q.withYjsUpdates != nil,
			_q.withVersions != nil,
			_q.withWikiPageVersions != nil,
			_q.withBlocks != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WikiPage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WikiPage{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *WikiPage, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCreator; query != nil {
		if err := _q.loadCreator(ctx, query, nodes, nil,
			func(n *WikiPage, e *User) { n.Edges.Creator = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUpdater; query != nil {
		if err := _q.loadUpdater(ctx, query, nodes, nil,
			func(n *WikiPage, e *User) { n.Edges.Updater = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withParent; query != nil {
		if err := _q.loadParent(ctx, query, nodes, nil,
			func(n *WikiPage, e *WikiPage) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChildren; query != nil {
		if err := _q.loadChildren(ctx, query, nodes,
			func(n *WikiPage) { n.Edges.Children = []*WikiPage{} },
			func(n *WikiPage, e *WikiPage) { n.Edges.Children = append(n.Edges.Children, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withYjsUpdates; query != nil {
		if err := _q.loadYjsUpdates(ctx, query, nodes,
			func(n *WikiPage) { n.Edges.YjsUpdates = []*YjsUpdate{} },
			func(n *WikiPage, e *YjsUpdate) { n.Edges.YjsUpdates = append(n.Edges.YjsUpdates, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withVersions; query != nil {
		if err := _q.loadVersions(ctx, query, nodes,
			func(n *WikiPage) { n.Edges.Versions = []*PageVersion{} },
			func(n *WikiPage, e *PageVersion) { n.Edges.Versions = append(n.Edges.Versions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withWikiPageVersions; query != nil {
		if err := _q.loadWikiPageVersions(ctx, query, nodes,
			func(n *WikiPage) { n.Edges.WikiPageVersions = []*WikiPageVersion{} },
			func(n *WikiPage, e *WikiPageVersion) { n.Edges.WikiPageVersions = append(n.Edges.WikiPageVersions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBlocks; query != nil {
		if err := _q.loadBlocks(ctx, query, nodes,
			func(n *WikiPage) { n.Edges.Blocks = []*WikiBlock{} },
			func(n *WikiPage, e *WikiBlock) { n.Edges.Blocks = append(n.Edges.Blocks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *WikiPageQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*WikiPage, init func(*WikiPage), assign func(*WikiPage, *Project)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*WikiPage)
	for i := range nodes {
		fk := nodes[i].ProjectID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WikiPageQuery) loadCreator(ctx context.Context, query *UserQuery, nodes []*WikiPage, init func(*WikiPage), assign func(*WikiPage, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*WikiPage)
	for i := range nodes {
		fk := nodes[i].CreatedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "created_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WikiPageQuery) loadUpdater(ctx context.Context, query *UserQuery, nodes []*WikiPage, init func(*WikiPage), assign func(*WikiPage, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*WikiPage)
	for i := range nodes {
		if nodes[i].UpdatedBy == nil {
			continue
		}
		fk := *nodes[i].UpdatedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "updated_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WikiPageQuery) loadParent(ctx context.Context, query *WikiPageQuery, nodes []*WikiPage, init func(*WikiPage), assign func(*WikiPage, *WikiPage)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*WikiPage)
	for i := range nodes {
		if nodes[i].ParentID == nil {
			continue
		}
		fk := *nodes[i].ParentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(wikipage.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "parent_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *WikiPageQuery) loadChildren(ctx context.Context, query *WikiPageQuery, nodes []*WikiPage, init func(*WikiPage), assign func(*WikiPage, *WikiPage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*WikiPage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(wikipage.FieldParentID)
	}
	query.Where(predicate.WikiPage(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(wikipage.ChildrenColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentID
		if fk == nil {
			return fmt.Errorf(`foreign-key "parent_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parent_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *WikiPageQuery) loadYjsUpdates(ctx context.Context, query *YjsUpdateQuery, nodes []*WikiPage, init func(*WikiPage), assign func(*WikiPage, *YjsUpdate)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*WikiPage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(yjsupdate.FieldPageID)
	}
	query.Where(predicate.YjsUpdate(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(wikipage.YjsUpdatesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PageID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "page_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *WikiPageQuery) loadVersions(ctx context.Context, query *PageVersionQuery, nodes []*WikiPage, init func(*WikiPage), assign func(*WikiPage, *PageVersion)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*WikiPage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(pageversion.FieldPageID)
	}
	query.Where(predicate.PageVersion(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(wikipage.VersionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PageID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "page_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *WikiPageQuery) loadWikiPageVersions(ctx context.Context, query *WikiPageVersionQuery, nodes []*WikiPage, init func(*WikiPage), assign func(*WikiPage, *WikiPageVersion)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*WikiPage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(wikipageversion.FieldWikiPageID)
	}
	query.Where(predicate.WikiPageVersion(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(wikipage.WikiPageVersionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WikiPageID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "wiki_page_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *WikiPageQuery) loadBlocks(ctx context.Context, query *WikiBlockQuery, nodes []*WikiPage, init func(*WikiPage), assign func(*WikiPage, *WikiBlock)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*WikiPage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(wikiblock.FieldPageID)
	}
	query.Where(predicate.WikiBlock(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(wikipage.BlocksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PageID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "page_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *WikiPageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *WikiPageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(wikipage.Table, wikipage.Columns, sqlgraph.NewFieldSpec(wikipage.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wikipage.FieldID)
		for i := range fields {
			if fields[i] != wikipage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProject != nil {
			_spec.Node.AddColumnOnce(wikipage.FieldProjectID)
		}
		if _q.withCreator != nil {
			_spec.Node.AddColumnOnce(wikipage.FieldCreatedBy)
		}
		if _q.withUpdater != nil {
			_spec.Node.AddColumnOnce(wikipage.FieldUpdatedBy)
		}
		if _q.withParent != nil {
			_spec.Node.AddColumnOnce(wikipage.FieldParentID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *WikiPageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(wikipage.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = wikipage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WikiPageGroupBy is the group-by builder for WikiPage entities.
type WikiPageGroupBy struct {
	selector
	build *WikiPageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *WikiPageGroupBy) Aggregate(fns ...AggregateFunc) *WikiPageGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *WikiPageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WikiPageQuery, *WikiPageGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *WikiPageGroupBy) sqlScan(ctx context.Context, root *WikiPageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WikiPageSelect is the builder for selecting fields of WikiPage entities.
type WikiPageSelect struct {
	*WikiPageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *WikiPageSelect) Aggregate(fns ...AggregateFunc) *WikiPageSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *WikiPageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WikiPageQuery, *WikiPageSelect](ctx, _s.WikiPageQuery, _s, _s.inters, v)
}

func (_s *WikiPageSelect) sqlScan(ctx context.Context, root *WikiPageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
