// Code generated by ent, DO NOT EDIT.

package task

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the task type in the database.
	Label = "task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldTaskNumber holds the string denoting the task_number field in the database.
	FieldTaskNumber = "task_number"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSwimLaneID holds the string denoting the swim_lane_id field in the database.
	FieldSwimLaneID = "swim_lane_id"
	// FieldSprintID holds the string denoting the sprint_id field in the database.
	FieldSprintID = "sprint_id"
	// FieldAssigneeID holds the string denoting the assignee_id field in the database.
	FieldAssigneeID = "assignee_id"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldEstimatedHours holds the string denoting the estimated_hours field in the database.
	FieldEstimatedHours = "estimated_hours"
	// FieldActualHours holds the string denoting the actual_hours field in the database.
	FieldActualHours = "actual_hours"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldDueDate holds the string denoting the due_date field in the database.
	FieldDueDate = "due_date"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeSwimLane holds the string denoting the swim_lane edge name in mutations.
	EdgeSwimLane = "swim_lane"
	// EdgeSprint holds the string denoting the sprint edge name in mutations.
	EdgeSprint = "sprint"
	// EdgeAssignee holds the string denoting the assignee edge name in mutations.
	EdgeAssignee = "assignee"
	// EdgeComments holds the string denoting the comments edge name in mutations.
	EdgeComments = "comments"
	// EdgeAttachments holds the string denoting the attachments edge name in mutations.
	EdgeAttachments = "attachments"
	// EdgeTaskTags holds the string denoting the task_tags edge name in mutations.
	EdgeTaskTags = "task_tags"
	// EdgeTaskAssignees holds the string denoting the task_assignees edge name in mutations.
	EdgeTaskAssignees = "task_assignees"
	// Table holds the table name of the task in the database.
	Table = "tasks"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "tasks"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// SwimLaneTable is the table that holds the swim_lane relation/edge.
	SwimLaneTable = "tasks"
	// SwimLaneInverseTable is the table name for the SwimLane entity.
	// It exists in this package in order to avoid circular dependency with the "swimlane" package.
	SwimLaneInverseTable = "swim_lanes"
	// SwimLaneColumn is the table column denoting the swim_lane relation/edge.
	SwimLaneColumn = "swim_lane_id"
	// SprintTable is the table that holds the sprint relation/edge.
	SprintTable = "tasks"
	// SprintInverseTable is the table name for the Sprint entity.
	// It exists in this package in order to avoid circular dependency with the "sprint" package.
	SprintInverseTable = "sprints"
	// SprintColumn is the table column denoting the sprint relation/edge.
	SprintColumn = "sprint_id"
	// AssigneeTable is the table that holds the assignee relation/edge.
	AssigneeTable = "tasks"
	// AssigneeInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AssigneeInverseTable = "users"
	// AssigneeColumn is the table column denoting the assignee relation/edge.
	AssigneeColumn = "assignee_id"
	// CommentsTable is the table that holds the comments relation/edge.
	CommentsTable = "task_comments"
	// CommentsInverseTable is the table name for the TaskComment entity.
	// It exists in this package in order to avoid circular dependency with the "taskcomment" package.
	CommentsInverseTable = "task_comments"
	// CommentsColumn is the table column denoting the comments relation/edge.
	CommentsColumn = "task_id"
	// AttachmentsTable is the table that holds the attachments relation/edge.
	AttachmentsTable = "task_attachments"
	// AttachmentsInverseTable is the table name for the TaskAttachment entity.
	// It exists in this package in order to avoid circular dependency with the "taskattachment" package.
	AttachmentsInverseTable = "task_attachments"
	// AttachmentsColumn is the table column denoting the attachments relation/edge.
	AttachmentsColumn = "task_id"
	// TaskTagsTable is the table that holds the task_tags relation/edge.
	TaskTagsTable = "task_tags"
	// TaskTagsInverseTable is the table name for the TaskTag entity.
	// It exists in this package in order to avoid circular dependency with the "tasktag" package.
	TaskTagsInverseTable = "task_tags"
	// TaskTagsColumn is the table column denoting the task_tags relation/edge.
	TaskTagsColumn = "task_id"
	// TaskAssigneesTable is the table that holds the task_assignees relation/edge.
	TaskAssigneesTable = "task_assignees"
	// TaskAssigneesInverseTable is the table name for the TaskAssignee entity.
	// It exists in this package in order to avoid circular dependency with the "taskassignee" package.
	TaskAssigneesInverseTable = "task_assignees"
	// TaskAssigneesColumn is the table column denoting the task_assignees relation/edge.
	TaskAssigneesColumn = "task_id"
)

// Columns holds all SQL columns for task fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldTaskNumber,
	FieldTitle,
	FieldDescription,
	FieldStatus,
	FieldSwimLaneID,
	FieldSprintID,
	FieldAssigneeID,
	FieldPriority,
	FieldEstimatedHours,
	FieldActualHours,
	FieldStartDate,
	FieldDueDate,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Task queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByTaskNumber orders the results by the task_number field.
func ByTaskNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskNumber, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySwimLaneID orders the results by the swim_lane_id field.
func BySwimLaneID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSwimLaneID, opts...).ToFunc()
}

// BySprintID orders the results by the sprint_id field.
func BySprintID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSprintID, opts...).ToFunc()
}

// ByAssigneeID orders the results by the assignee_id field.
func ByAssigneeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAssigneeID, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByEstimatedHours orders the results by the estimated_hours field.
func ByEstimatedHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedHours, opts...).ToFunc()
}

// ByActualHours orders the results by the actual_hours field.
func ByActualHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualHours, opts...).ToFunc()
}

// ByStartDate orders the results by the start_date field.
func ByStartDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartDate, opts...).ToFunc()
}

// ByDueDate orders the results by the due_date field.
func ByDueDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDueDate, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// BySwimLaneField orders the results by swim_lane field.
func BySwimLaneField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSwimLaneStep(), sql.OrderByField(field, opts...))
	}
}

// BySprintField orders the results by sprint field.
func BySprintField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSprintStep(), sql.OrderByField(field, opts...))
	}
}

// ByAssigneeField orders the results by assignee field.
func ByAssigneeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssigneeStep(), sql.OrderByField(field, opts...))
	}
}

// ByCommentsCount orders the results by comments count.
func ByCommentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCommentsStep(), opts...)
	}
}

// ByComments orders the results by comments terms.
func ByComments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAttachmentsCount orders the results by attachments count.
func ByAttachmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttachmentsStep(), opts...)
	}
}

// ByAttachments orders the results by attachments terms.
func ByAttachments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttachmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTaskTagsCount orders the results by task_tags count.
func ByTaskTagsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTaskTagsStep(), opts...)
	}
}

// ByTaskTags orders the results by task_tags terms.
func ByTaskTags(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskTagsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTaskAssigneesCount orders the results by task_assignees count.
func ByTaskAssigneesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTaskAssigneesStep(), opts...)
	}
}

// ByTaskAssignees orders the results by task_assignees terms.
func ByTaskAssignees(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskAssigneesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newSwimLaneStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SwimLaneInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SwimLaneTable, SwimLaneColumn),
	)
}
func newSprintStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SprintInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SprintTable, SprintColumn),
	)
}
func newAssigneeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssigneeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AssigneeTable, AssigneeColumn),
	)
}
func newCommentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
	)
}
func newAttachmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttachmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
	)
}
func newTaskTagsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskTagsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TaskTagsTable, TaskTagsColumn),
	)
}
func newTaskAssigneesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskAssigneesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TaskAssigneesTable, TaskAssigneesColumn),
	)
}
