// Code generated by ent, DO NOT EDIT.

package task

import (
	"taskai/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldProjectID, v))
}

// TaskNumber applies equality check predicate on the "task_number" field. It's identical to TaskNumberEQ.
func TaskNumber(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTaskNumber, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldStatus, v))
}

// SwimLaneID applies equality check predicate on the "swim_lane_id" field. It's identical to SwimLaneIDEQ.
func SwimLaneID(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldSwimLaneID, v))
}

// SprintID applies equality check predicate on the "sprint_id" field. It's identical to SprintIDEQ.
func SprintID(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldSprintID, v))
}

// AssigneeID applies equality check predicate on the "assignee_id" field. It's identical to AssigneeIDEQ.
func AssigneeID(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAssigneeID, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPriority, v))
}

// EstimatedHours applies equality check predicate on the "estimated_hours" field. It's identical to EstimatedHoursEQ.
func EstimatedHours(v float64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldEstimatedHours, v))
}

// ActualHours applies equality check predicate on the "actual_hours" field. It's identical to ActualHoursEQ.
func ActualHours(v float64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldActualHours, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldStartDate, v))
}

// DueDate applies equality check predicate on the "due_date" field. It's identical to DueDateEQ.
func DueDate(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDueDate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldProjectID, vs...))
}

// TaskNumberEQ applies the EQ predicate on the "task_number" field.
func TaskNumberEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTaskNumber, v))
}

// TaskNumberNEQ applies the NEQ predicate on the "task_number" field.
func TaskNumberNEQ(v int) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldTaskNumber, v))
}

// TaskNumberIn applies the In predicate on the "task_number" field.
func TaskNumberIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldTaskNumber, vs...))
}

// TaskNumberNotIn applies the NotIn predicate on the "task_number" field.
func TaskNumberNotIn(vs ...int) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldTaskNumber, vs...))
}

// TaskNumberGT applies the GT predicate on the "task_number" field.
func TaskNumberGT(v int) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldTaskNumber, v))
}

// TaskNumberGTE applies the GTE predicate on the "task_number" field.
func TaskNumberGTE(v int) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldTaskNumber, v))
}

// TaskNumberLT applies the LT predicate on the "task_number" field.
func TaskNumberLT(v int) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldTaskNumber, v))
}

// TaskNumberLTE applies the LTE predicate on the "task_number" field.
func TaskNumberLTE(v int) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldTaskNumber, v))
}

// TaskNumberIsNil applies the IsNil predicate on the "task_number" field.
func TaskNumberIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldTaskNumber))
}

// TaskNumberNotNil applies the NotNil predicate on the "task_number" field.
func TaskNumberNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldTaskNumber))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldStatus, v))
}

// SwimLaneIDEQ applies the EQ predicate on the "swim_lane_id" field.
func SwimLaneIDEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldSwimLaneID, v))
}

// SwimLaneIDNEQ applies the NEQ predicate on the "swim_lane_id" field.
func SwimLaneIDNEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldSwimLaneID, v))
}

// SwimLaneIDIn applies the In predicate on the "swim_lane_id" field.
func SwimLaneIDIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldSwimLaneID, vs...))
}

// SwimLaneIDNotIn applies the NotIn predicate on the "swim_lane_id" field.
func SwimLaneIDNotIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldSwimLaneID, vs...))
}

// SwimLaneIDIsNil applies the IsNil predicate on the "swim_lane_id" field.
func SwimLaneIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldSwimLaneID))
}

// SwimLaneIDNotNil applies the NotNil predicate on the "swim_lane_id" field.
func SwimLaneIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldSwimLaneID))
}

// SprintIDEQ applies the EQ predicate on the "sprint_id" field.
func SprintIDEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldSprintID, v))
}

// SprintIDNEQ applies the NEQ predicate on the "sprint_id" field.
func SprintIDNEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldSprintID, v))
}

// SprintIDIn applies the In predicate on the "sprint_id" field.
func SprintIDIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldSprintID, vs...))
}

// SprintIDNotIn applies the NotIn predicate on the "sprint_id" field.
func SprintIDNotIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldSprintID, vs...))
}

// SprintIDIsNil applies the IsNil predicate on the "sprint_id" field.
func SprintIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldSprintID))
}

// SprintIDNotNil applies the NotNil predicate on the "sprint_id" field.
func SprintIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldSprintID))
}

// AssigneeIDEQ applies the EQ predicate on the "assignee_id" field.
func AssigneeIDEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldAssigneeID, v))
}

// AssigneeIDNEQ applies the NEQ predicate on the "assignee_id" field.
func AssigneeIDNEQ(v int64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldAssigneeID, v))
}

// AssigneeIDIn applies the In predicate on the "assignee_id" field.
func AssigneeIDIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldAssigneeID, vs...))
}

// AssigneeIDNotIn applies the NotIn predicate on the "assignee_id" field.
func AssigneeIDNotIn(vs ...int64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldAssigneeID, vs...))
}

// AssigneeIDIsNil applies the IsNil predicate on the "assignee_id" field.
func AssigneeIDIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldAssigneeID))
}

// AssigneeIDNotNil applies the NotNil predicate on the "assignee_id" field.
func AssigneeIDNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldAssigneeID))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v string) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...string) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v string) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v string) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v string) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v string) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldPriority, v))
}

// PriorityContains applies the Contains predicate on the "priority" field.
func PriorityContains(v string) predicate.Task {
	return predicate.Task(sql.FieldContains(FieldPriority, v))
}

// PriorityHasPrefix applies the HasPrefix predicate on the "priority" field.
func PriorityHasPrefix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasPrefix(FieldPriority, v))
}

// PriorityHasSuffix applies the HasSuffix predicate on the "priority" field.
func PriorityHasSuffix(v string) predicate.Task {
	return predicate.Task(sql.FieldHasSuffix(FieldPriority, v))
}

// PriorityEqualFold applies the EqualFold predicate on the "priority" field.
func PriorityEqualFold(v string) predicate.Task {
	return predicate.Task(sql.FieldEqualFold(FieldPriority, v))
}

// PriorityContainsFold applies the ContainsFold predicate on the "priority" field.
func PriorityContainsFold(v string) predicate.Task {
	return predicate.Task(sql.FieldContainsFold(FieldPriority, v))
}

// EstimatedHoursEQ applies the EQ predicate on the "estimated_hours" field.
func EstimatedHoursEQ(v float64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldEstimatedHours, v))
}

// EstimatedHoursNEQ applies the NEQ predicate on the "estimated_hours" field.
func EstimatedHoursNEQ(v float64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldEstimatedHours, v))
}

// EstimatedHoursIn applies the In predicate on the "estimated_hours" field.
func EstimatedHoursIn(vs ...float64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldEstimatedHours, vs...))
}

// EstimatedHoursNotIn applies the NotIn predicate on the "estimated_hours" field.
func EstimatedHoursNotIn(vs ...float64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldEstimatedHours, vs...))
}

// EstimatedHoursGT applies the GT predicate on the "estimated_hours" field.
func EstimatedHoursGT(v float64) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldEstimatedHours, v))
}

// EstimatedHoursGTE applies the GTE predicate on the "estimated_hours" field.
func EstimatedHoursGTE(v float64) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldEstimatedHours, v))
}

// EstimatedHoursLT applies the LT predicate on the "estimated_hours" field.
func EstimatedHoursLT(v float64) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldEstimatedHours, v))
}

// EstimatedHoursLTE applies the LTE predicate on the "estimated_hours" field.
func EstimatedHoursLTE(v float64) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldEstimatedHours, v))
}

// EstimatedHoursIsNil applies the IsNil predicate on the "estimated_hours" field.
func EstimatedHoursIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldEstimatedHours))
}

// EstimatedHoursNotNil applies the NotNil predicate on the "estimated_hours" field.
func EstimatedHoursNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldEstimatedHours))
}

// ActualHoursEQ applies the EQ predicate on the "actual_hours" field.
func ActualHoursEQ(v float64) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldActualHours, v))
}

// ActualHoursNEQ applies the NEQ predicate on the "actual_hours" field.
func ActualHoursNEQ(v float64) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldActualHours, v))
}

// ActualHoursIn applies the In predicate on the "actual_hours" field.
func ActualHoursIn(vs ...float64) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldActualHours, vs...))
}

// ActualHoursNotIn applies the NotIn predicate on the "actual_hours" field.
func ActualHoursNotIn(vs ...float64) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldActualHours, vs...))
}

// ActualHoursGT applies the GT predicate on the "actual_hours" field.
func ActualHoursGT(v float64) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldActualHours, v))
}

// ActualHoursGTE applies the GTE predicate on the "actual_hours" field.
func ActualHoursGTE(v float64) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldActualHours, v))
}

// ActualHoursLT applies the LT predicate on the "actual_hours" field.
func ActualHoursLT(v float64) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldActualHours, v))
}

// ActualHoursLTE applies the LTE predicate on the "actual_hours" field.
func ActualHoursLTE(v float64) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldActualHours, v))
}

// ActualHoursIsNil applies the IsNil predicate on the "actual_hours" field.
func ActualHoursIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldActualHours))
}

// ActualHoursNotNil applies the NotNil predicate on the "actual_hours" field.
func ActualHoursNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldActualHours))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldStartDate, v))
}

// StartDateIsNil applies the IsNil predicate on the "start_date" field.
func StartDateIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldStartDate))
}

// StartDateNotNil applies the NotNil predicate on the "start_date" field.
func StartDateNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldStartDate))
}

// DueDateEQ applies the EQ predicate on the "due_date" field.
func DueDateEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldDueDate, v))
}

// DueDateNEQ applies the NEQ predicate on the "due_date" field.
func DueDateNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldDueDate, v))
}

// DueDateIn applies the In predicate on the "due_date" field.
func DueDateIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldDueDate, vs...))
}

// DueDateNotIn applies the NotIn predicate on the "due_date" field.
func DueDateNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldDueDate, vs...))
}

// DueDateGT applies the GT predicate on the "due_date" field.
func DueDateGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldDueDate, v))
}

// DueDateGTE applies the GTE predicate on the "due_date" field.
func DueDateGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldDueDate, v))
}

// DueDateLT applies the LT predicate on the "due_date" field.
func DueDateLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldDueDate, v))
}

// DueDateLTE applies the LTE predicate on the "due_date" field.
func DueDateLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldDueDate, v))
}

// DueDateIsNil applies the IsNil predicate on the "due_date" field.
func DueDateIsNil() predicate.Task {
	return predicate.Task(sql.FieldIsNull(FieldDueDate))
}

// DueDateNotNil applies the NotNil predicate on the "due_date" field.
func DueDateNotNil() predicate.Task {
	return predicate.Task(sql.FieldNotNull(FieldDueDate))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Task {
	return predicate.Task(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Task {
	return predicate.Task(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSwimLane applies the HasEdge predicate on the "swim_lane" edge.
func HasSwimLane() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SwimLaneTable, SwimLaneColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSwimLaneWith applies the HasEdge predicate on the "swim_lane" edge with a given conditions (other predicates).
func HasSwimLaneWith(preds ...predicate.SwimLane) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newSwimLaneStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSprint applies the HasEdge predicate on the "sprint" edge.
func HasSprint() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SprintTable, SprintColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSprintWith applies the HasEdge predicate on the "sprint" edge with a given conditions (other predicates).
func HasSprintWith(preds ...predicate.Sprint) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newSprintStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignee applies the HasEdge predicate on the "assignee" edge.
func HasAssignee() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssigneeTable, AssigneeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssigneeWith applies the HasEdge predicate on the "assignee" edge with a given conditions (other predicates).
func HasAssigneeWith(preds ...predicate.User) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newAssigneeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasComments applies the HasEdge predicate on the "comments" edge.
func HasComments() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommentsWith applies the HasEdge predicate on the "comments" edge with a given conditions (other predicates).
func HasCommentsWith(preds ...predicate.TaskComment) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newCommentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttachments applies the HasEdge predicate on the "attachments" edge.
func HasAttachments() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttachmentsWith applies the HasEdge predicate on the "attachments" edge with a given conditions (other predicates).
func HasAttachmentsWith(preds ...predicate.TaskAttachment) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newAttachmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTaskTags applies the HasEdge predicate on the "task_tags" edge.
func HasTaskTags() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TaskTagsTable, TaskTagsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskTagsWith applies the HasEdge predicate on the "task_tags" edge with a given conditions (other predicates).
func HasTaskTagsWith(preds ...predicate.TaskTag) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newTaskTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTaskAssignees applies the HasEdge predicate on the "task_assignees" edge.
func HasTaskAssignees() predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TaskAssigneesTable, TaskAssigneesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskAssigneesWith applies the HasEdge predicate on the "task_assignees" edge with a given conditions (other predicates).
func HasTaskAssigneesWith(preds ...predicate.TaskAssignee) predicate.Task {
	return predicate.Task(func(s *sql.Selector) {
		step := newTaskAssigneesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Task) predicate.Task {
	return predicate.Task(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Task) predicate.Task {
	return predicate.Task(sql.NotPredicates(p))
}
