// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// CloudinaryCredential is the predicate function for cloudinarycredential builders.
type CloudinaryCredential func(*sql.Selector)

// EmailProvider is the predicate function for emailprovider builders.
type EmailProvider func(*sql.Selector)

// Invite is the predicate function for invite builders.
type Invite func(*sql.Selector)

// PageVersion is the predicate function for pageversion builders.
type PageVersion func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectMember is the predicate function for projectmember builders.
type ProjectMember func(*sql.Selector)

// Sprint is the predicate function for sprint builders.
type Sprint func(*sql.Selector)

// SwimLane is the predicate function for swimlane builders.
type SwimLane func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskAssignee is the predicate function for taskassignee builders.
type TaskAssignee func(*sql.Selector)

// TaskAttachment is the predicate function for taskattachment builders.
type TaskAttachment func(*sql.Selector)

// TaskComment is the predicate function for taskcomment builders.
type TaskComment func(*sql.Selector)

// TaskTag is the predicate function for tasktag builders.
type TaskTag func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)

// TeamInvitation is the predicate function for teaminvitation builders.
type TeamInvitation func(*sql.Selector)

// TeamMember is the predicate function for teammember builders.
type TeamMember func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserActivity is the predicate function for useractivity builders.
type UserActivity func(*sql.Selector)

// WikiBlock is the predicate function for wikiblock builders.
type WikiBlock func(*sql.Selector)

// WikiPage is the predicate function for wikipage builders.
type WikiPage func(*sql.Selector)

// YjsUpdate is the predicate function for yjsupdate builders.
type YjsUpdate func(*sql.Selector)
